mwouts/jupytext

- tests/test_unicode.py
Follows Python porting best practice, [use feature detection instead of version detection](https://docs.python.org/3/howto/pyporting.html#use-feature-detection-instead-of-version-detection).
__unicode__ was removed in Python 3 because all __str__ are Unicode.
[flake8](http://flake8.pycqa.org) testing of https://github.com/mwouts/jupytext on Python 3.7.0
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./.jupyter/jupyter_notebook_config.py:1:1: F821 undefined name 'c'
c.NotebookApp.contents_manager_class = 'jupytext.TextFileContentsManager'
^
./tests/test_unicode.py:15:65: F821 undefined name 'unicode'
assert cell.source == '' or isinstance(cell.source, unicode)
^
./tests/mirror/jupyter_again.py:32:1: E999 SyntaxError: invalid syntax
?next
^
1 …
```
> Define unicode in Python 3

- .jupyter/jupyter_notebook_config.py
- .travis.yml
- tests/mirror/jupyter_again.py
Add [flake8](http://flake8.pycqa.org) tests to find Python syntax errors and undefined names.
__E901,E999,F821,F822,F823__ are the "_showstopper_" flake8 issues that can halt the runtime with a SyntaxError, NameError, etc. Most other flake8 issues are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree
> Travis CI: Update pypy, Add flake8 tests

- jupytext/cell_metadata.py
- tests/test_read_simple_percent.py
Currently, if you have a comment like this in a program when converting from "py:percent":
```python
path = fastai.untar_data(fastai.URLs.MNIST_TINY)
print("data path:", path)
```
jupytext will crash. This fix keeps it from crashing, and also identifies the cell as code.
> Allow more flexible code identification

- HISTORY.rst
- jupytext/cell_metadata.py
- jupytext/cell_reader.py
- jupytext/combine.py
- jupytext/contentsmanager.py
- jupytext/formats.py
- jupytext/jupytext.py
- jupytext/languages.py
- jupytext/version.py
- tests/notebooks/ipynb_bash/sample_bash_notebook.ipynb
- tests/notebooks/mirror/ipynb_to_percent/ir_notebook.low.r
- tests/notebooks/mirror/ipynb_to_percent/sample_bash_notebook.sh
- tests/notebooks/mirror/ipynb_to_script/ir_notebook.low.r
- tests/notebooks/mirror/ipynb_to_script/sample_bash_notebook.sh
- tests/notebooks/mirror/ipynb_to_spin/ir_notebook.R
- tests/notebooks/mirror/ipynb_to_spin/ir_notebook.low.r
- tests/test_escape_magics.py
- tests/test_ipynb_to_R.py
- tests/test_mirror.py
- tests/test_read_simple_R.py
- tests/test_read_simple_python.py
**Improvements**
- `bash` scripts as notebooks (#127)
- R scripts with `.r` extension are supported (#122)
- Jupytext selects the first kernel that matches the language (#120)
> Version 0.8.5

- requirements-dev.txt
Travis CI is currently failing with error message
```
Plugin 'pytest_cov' could not be loaded: (pytest 3.3.0 (/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages), Requirement.parse('pytest>=3.6'))!
```
As in the pytest-cov release notes I find the mention _Dropped support for Python < 3.4, Pytest < 3.5 and Coverage < 4.4_ for version 2.6, we'll try with the previous release.
> Require pytest-cov==2.5.1

- jupytext/languages.py
- tests/notebooks/mirror/ipynb_to_percent/Reference Guide for Calysto Scheme.scm
- tests/notebooks/mirror/ipynb_to_script/Reference Guide for Calysto Scheme.scm
- tests/test_mirror.py
- tests/test_read_simple_scheme.py
Scheme support is already in place.  This PR associates the `.scm` file extension with Scheme scripts, and extends the test to test that extension along with the existing `.ss` extension.
> Associate `.scm` file extension with Scheme scripts

- jupytext/__init__.py
Only load the jupytext.TextFileContentsManager as contents manager
if the configured class is not already an instance of it.
We use a subclass of TextFileContentsManager to extend the rename and delete methods. However, our subclass is replaced by the provided TextFileContentsManager since it is not exactly that class.
This allows custom classes if they are a subclass of TextFileContentsManager.
> Also allow subclasses of TextFileContentsManager

- README.md
Add brief summary of the `percent` and `light` formats in the introduction.
The various format-related terms appear later in the README without introduction or motivation. In particular the first appearance of "light" is in the refactoring section: we select "Pair Notebook with a light Script". I think these terms need to be introduced in a more general context before use, which I attempted in this edit.
I also made an attempt to clarify I few other statements that I stumbled over on an initial read and caught a few typos.
> Update README.md to mention format options in the introduction

- jupytext/languages.py
- tests/notebooks/ipynb_scala/simple_scala_notebook.ipynb
- tests/notebooks/mirror/ipynb_to_percent/simple_scala_notebook.scala
- tests/notebooks/mirror/ipynb_to_script/simple_scala_notebook.scala
- tests/test_mirror.py
This PR adds the scala syntax support to the jupytext extension
> Adding scala support to jupytext extension

- HISTORY.rst
- docs/using-cli.md
- jupytext/__init__.py
- jupytext/cli.py
- jupytext/jupytext.py
- jupytext/version.py
- tests/test_auto_ext.py
- tests/test_black.py
- tests/test_cli.py
- tests/test_contentsmanager.py
- tests/test_jupytext_errors.py
- tests/test_knitr_spin.py
- tests/test_load_multiple.py
- tests/test_mirror.py
- tests/test_pep8.py
- tests/test_read_simple_ipynb.py
- tests/test_save_multiple.py
- tests/test_unicode.py
- tests/test_write_does_not_modify_notebook.py
- Previous readf/writef functions marked as deprecated
- They are replaced with read/write which can take a file name, like `nbformat`'s functions. Argument `fmt` goes after the `nbformat` version for improved compatibility with `read` and `write` of the `nbformat` package.
> Jupytext read/write functions as drop in replacement for nbformat's ones

- HISTORY.rst
- README.md
- docs/using-cli.md
- jupytext/cli.py
- jupytext/jupytext.py
- jupytext/kernels.py
- jupytext/languages.py
- requirements-dev.txt
- tests/test_cli.py
- tests/test_execute.py
- tests/test_read_simple_markdown.py
- tests/utils.py
- New `--execute` option in Jupytext CLI (#231)
- The `--set-formats` option in Jupytext CLI also triggers `--sync`, allowing shorter commands.
> Jupytext execute

- HISTORY.rst
- jupyter-config/jupyter_server_config.d/jupytext.json
- jupytext/__init__.py
- jupytext/contentsmanager.py
- jupytext/version.py
- setup.py
Jupytext's CM is derived directly from the NotebookApp (or ServerApp)'s contents manager.
This should allow Jupytext to be used with Voila - see #270
(@SylvainCorlay, what else do we need to do for this?)
> Derive jupytext cm from app cm

- HISTORY.rst
- jupytext/contentsmanager.py
- requirements.txt
- setup.py
- tests/conftest.py
- tests/test_active_cells.py
- tests/test_cli.py
- tests/test_escape_magics.py
- tests/test_header.py
- tests/test_load_multiple.py
- tests/test_mirror.py
- tests/test_read_simple_markdown.py
- tests/test_rmd_to_ipynb.py
- tests/test_trust_notebook.py
In Python 3, mock is available in base Python as `unittest.mock`. See #279
> Remove the dependency on mock

- README.md
- docs/using-cli.md
I was getting an error when following blindly the doc:
```
jupytext: error: argument --set-formats: expected one argument
usage: jupytext [-h] [--from INPUT_FORMAT] [--pre-commit] [--to TO]
[--format-options FORMAT_OPTIONS] [--set-formats SET_FORMATS]
[--set-kernel SET_KERNEL] [--update-metadata UPDATE_METADATA]
[-o OUTPUT] [--update]
[--version | --paired-paths | --sync | --test | --test-strict]
[--stop] [--pipe PIPE] [--check CHECK] [--pipe-fmt PIPE_FMT]
[--quiet]
[notebooks [notebooks ...]]
jupytext: error: argument --set-formats: expected one argument
```
> Fix typo in command line arguments doc

- .travis.yml
As it fails with Python 3.4 on Travis with this error
FileNotFoundError: [Errno 2] No such file or directory: '/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/six-1.10.0.dist-info/METADATA'
> pip install . is optional

- jupytext/cell_reader.py
Fix #301 by intercepting the `SyntaxError` exception that occurs in Python 2.7
> Fix Travis on Python 2.7

- .travis.yml
Python 2.6 is not available any more on Travis. We'll have to find a better way to test Jupytext with Pandoc from conda-forge - see #313 !
> Remove Python 2.6 on Travis

- docs/formats.md
Thanks for making jupytext! It's really facilitating my git workflow for notebooks!
I was reading through the code cell support in other editors and noticed that the vscode extension has been deprecated and the functionality included in vscode, so I removed that link. I also updated the other links to point directly to the doc sections about code cells for the respective IDE.
> Update code cell IDE doc links

- README.md
- docs/install.md
Improve the README.md documentation installation instructions in order to avoid the problem reported in #298.
> add instructions in the docs to enable Jupytext extension in Jupyter Lab

- jupytext/pandoc.py
- requirements-dev.txt
> pkg_resources is an optional dependency

- jupytext/cell_reader.py
- tests/notebooks/ipynb_py/cat_variable.ipynb
- tests/notebooks/mirror/ipynb_to_Rmd/cat_variable.Rmd
- tests/notebooks/mirror/ipynb_to_hydrogen/cat_variable.py
- tests/notebooks/mirror/ipynb_to_md/cat_variable.md
- tests/notebooks/mirror/ipynb_to_pandoc/cat_variable.md
- tests/notebooks/mirror/ipynb_to_percent/cat_variable.py
- tests/notebooks/mirror/ipynb_to_script/cat_variable.py
- tests/notebooks/mirror/ipynb_to_script_vim_folding_markers/cat_variable.py
- tests/notebooks/mirror/ipynb_to_script_vscode_folding_markers/cat_variable.py
- tests/test_cli.py
When a code cell contained a magic command like `cat` or `ls`, the round-trip conversion through the `py` format changed the cell type to markdown (#339).
The correction is to use the same function (`is_magic`) to detect when a line contains a Jupyter magic, both at the time of encoding and decoding it.
> Fix inconsistent cell type

- docs/faq.md
- docs/using-server.md
I followed the [original solution](https://stackoverflow.com/questions/25631344/turn-off-autosave-in-ipython-notebook/56549758#56549758) an it does not work anymore. Furthermore I find it is a bit an overkill to install jupyter_contrib_nbextension just to turn off autosave.
I tried [this solution](https://stackoverflow.com/a/45980165) with a fresh jupyter and it worked fine:
```sh
mkdir -p ~/.jupyter/custom
echo "Jupyter.notebook.set_autosave_interval(0)" > ~/.jupyter/custom/custom.js
```
> Change SO link to turn off autosave permanently in faq

- HISTORY.rst
- jupytext/languages.py
- jupytext/magics.py
- tests/notebooks/ipynb_rust/evcxr_jupyter_tour.ipynb
- tests/notebooks/mirror/ipynb_to_Rmd/evcxr_jupyter_tour.Rmd
- tests/notebooks/mirror/ipynb_to_md/evcxr_jupyter_tour.md
- tests/notebooks/mirror/ipynb_to_percent/evcxr_jupyter_tour.rs
- tests/notebooks/mirror/ipynb_to_script/evcxr_jupyter_tour.rs
- tests/test_mirror.py
- tests/test_read_simple_rust.py
I tried to follow the listed for "Add support for another language". I do have some questions about the last point though.
Evcxr has special commands, which are not valid Rust in any way. In contrast to Python magic cells they start with `:` instead of `%`, so they are not covered by the current logic for line magic.
From the code it looked like changing the variables `_MAGIC_RE`/`_MAGIC_FORCE_ESC_RE` might be the way to go here, but since I do not see any special casing there yet, I first wanted to know if that would be correct.
Here is a list of the supported magics in Evcxr. 
```
:vars             List bound variables and their types
:opt [level]      Toggle/set optimization level
:explain          Print explanation of last error
:clear            Clear all state, keeping compilation …
```
> Add support for Rust/Evxcr

- HISTORY.rst
- jupytext/cell_metadata.py
- jupytext/cell_reader.py
- jupytext/cell_to_text.py
- jupytext/compare.py
- jupytext/jupytext.py
- tests/notebooks/md/jupytext_markdown.md
- tests/notebooks/mirror/md_to_ipynb/jupytext_markdown.ipynb
- tests/notebooks/mirror/md_to_ipynb/plain_markdown.ipynb
- tests/test_active_cells.py
- tests/test_cell_metadata.py
- tests/test_cli.py
- tests/test_compare.py
- tests/test_contentsmanager.py
- tests/test_escape_magics.py
- tests/test_ipynb_to_R.py
- tests/test_ipynb_to_py.py
- tests/test_ipynb_to_rmd.py
- tests/test_jupytext_read.py
- tests/test_mirror.py
- tests/test_preserve_empty_cells.py
- tests/test_read_simple_markdown.py
- tests/test_read_simple_pandoc.py
- tests/test_read_simple_percent.py
- tests/test_read_simple_python.py
- tests/test_save_multiple.py
- Markdown cells can start with  or  (`.md` and `.markdown` files)
- Active/inactive cells behave the same in Markdown files than in the other formats #347 
- Shorter start of cell marker: `"# %% [md]"` for the `percent` format 
- All formats can now parse `key=value` metadata #344
> Markdown format update

- HISTORY.rst
- jupytext/cell_metadata.py
- jupytext/cell_reader.py
- jupytext/compare.py
- jupytext/languages.py
- tests/test_read_simple_markdown.py
- Improve the compare_notebook function (show the difference in cell content, and catch a missing line break)
- Code cells with a Jupyter language, and a `.noeval` attribute, are not turned into code cells in Jupyter #347
> Noeval attribute md

- jupytext/cli.py
- jupytext/formats.py
- jupytext/kernels.py
- jupytext/languages.py
- tests/test_auto_ext.py
- tests/test_black.py
- tests/test_cli.py
- Document default values (and add line breaks) in `jupytext --help`
- Compute the auto extension from the kernel specs, when language_info is not available
- Confirm with a test that `jupytext --pipe black *.md` works
- If really there's nothing we can do to compute the `.auto` extension, jupytext gives a more explicit message, and points out which option should be modified.
Closes #358
> Improve cli messages

- jupytext/cell_to_text.py
- tests/notebooks/ipynb_py/Line_breaks_in_LateX_305.ipynb
- tests/notebooks/mirror/ipynb_to_Rmd/Line_breaks_in_LateX_305.Rmd
- tests/notebooks/mirror/ipynb_to_hydrogen/Line_breaks_in_LateX_305.py
- tests/notebooks/mirror/ipynb_to_md/Line_breaks_in_LateX_305.md
- tests/notebooks/mirror/ipynb_to_percent/Line_breaks_in_LateX_305.py
- tests/notebooks/mirror/ipynb_to_script/Line_breaks_in_LateX_305.py
- tests/notebooks/mirror/ipynb_to_script_vim_folding_markers/Line_breaks_in_LateX_305.py
- tests/notebooks/mirror/ipynb_to_script_vscode_folding_markers/Line_breaks_in_LateX_305.py
- tests/notebooks/mirror/ipynb_to_sphinx/Line_breaks_in_LateX_305.py
- tests/test_cli.py
- tests/test_contentsmanager.py
- tests/test_mirror.py
- tests/utils.py
Test the LaTeX equation provided at #305 and make sure that the round trip works.
> Test backslash in markdown

- HISTORY.rst
- jupytext/cell_reader.py
- tests/test_read_simple_markdown.py
Code cells can start with ` ```python3` in Markdown files. In that case we insert a `%%python3` cell magic at the top of the cell.
Closes #365.
> Fix round trip to md with %%python3 cell magic

- CONTRIBUTING.md
- HISTORY.rst
- README.md
- docs/introduction.md
- jupytext/languages.py
- tests/notebooks/ipynb_robot/simple_robot_notebook.ipynb
- tests/notebooks/mirror/ipynb_to_Rmd/simple_robot_notebook.Rmd
- tests/notebooks/mirror/ipynb_to_hydrogen/simple_robot_notebook.robot
- tests/notebooks/mirror/ipynb_to_md/simple_robot_notebook.md
- tests/notebooks/mirror/ipynb_to_percent/simple_robot_notebook.robot
- tests/notebooks/mirror/ipynb_to_script/simple_robot_notebook.robot
- tests/test_mirror.py
> Add Robot Framework (.robot) -language support

- README.md
- jupytext/cell_reader.py
- jupytext/languages.py
- jupytext/version.py
LGTM reports one alert on the project:
This PR defines a new constant that contains all languages both in lower and upper case. Hopefully this will fix the alert.
> Fix one LGTM alert

- tests/test_cli.py
The pre-commit hook tests need a local install of Jupytext (e.g. `pip install -e .`)
> Fix tests on a fresh install

- docs/faq.md
This PR follows from the instruction given in #417 on how to remove pairing from notebooks (which is currently not documented). Please add more info/corrections if needed.
Thanks for creating `jupytext`!
> Add instructions on how to remove pairing

- CHANGELOG.md
- jupytext/cli.py
- tests/test_cli.py
> Ignore changes in the YAML header in jupytext --test

- jupytext/cli.py
- jupytext/formats.py
- jupytext/version.py
- tests/test_mirror.py
> Compute the script extension for each file

- jupytext/header.py
- tests/test_read_simple_rust.py
The shebang always starts with the sequence `#!` independent of the comment symbol of the programming language. Add a test with Rust, which uses `//` as the comment symbol.
The problem with the existing code is that it uses the comment symbol in the shebang line. The shebang can only start with `#!` though. This leads to two problems.
When parsing the shebang, when converting from text to notebook format, it uses a fixed offset of two characters to take the executable path ([`line[2:]`](https://github.com/mwouts/jupytext/pull/434/files#diff-e90356d1e1bc0107aa247e815ebc6147R148)), which fails if the comment is not only one character, like the two characters of `//`.
Similarly, when converting from notebook to text, it uses the comment symbol again and writes an invalid shebang.
The new …
> Fix shebang handling for languages with non-# comments

- tests/test_read_simple_python.py
This is a follow-up on #434 : we use the `no_jupytext_version_number` fixture rather than the custom filter.
> Use the `no_jupytext_version_number` fixture

- CHANGELOG.md
- jupytext/magics.py
- tests/test_read_simple_python.py
> Comment indented bash commands

- docs/using-cli.md
- tests/test_using_cli.py
--comment-magics is not available in version 1.4.1
> remove obsolete option --comment-magics

- CHANGELOG.md
- jupytext/kernels.py
- tests/test_cli.py
We now use os.path.samefile to determine if a given kernel matches the current python environment. This fixes a few tests when running `pytest` on Windows.
> Use os.path.samefile rather than os.path.normpath

- CHANGELOG.md
- jupytext/formats.py
- tests/test_cli.py
- tests/test_formats.py
`jupytext.read` and `jupytext.write` now give more meaningful errors when the format information is incorrect.
This closes #462.
> Check format in jupytext.read and jupytext.write

- CHANGELOG.md
- jupytext/stringparser.py
- tests/test_read_simple_percent.py
- tests/test_stringparser.py
Four consecutive quotes are a correct way to open multiline strings.
This fixes #460.
> Improve the string parser

- jupytext/formats.py
- jupytext/myst.py
- setup.py
- tests/test_ipynb_to_myst.py
Hey @mwouts, first just to clarify this should not be merged just yet. It is an update to use the (currently) pre-release ExecutableBookProject/MyST-Parser#123, which utilises [markdown-it-py](https://github.com/ExecutableBookProject/markdown-it-py), my shiny new markdown parser 😁 
As you can see, it does not affect any of the tests, and thus shouldn't be noticeable on the front-end.
> Update parsing of myst notebooks to new (markdown-it based) parser

- CHANGELOG.md
- docs/formats.md
- docs/using-cli.md
- tests/test_read_simple_markdown.py
> Add an example with custom notebook metadata

- jupytext/combine.py
This PR implements new rules for combining the outputs from the `.ipynb` notebook, with the inputs from the text notebook.
The matching rules are implemented at [`jupytext.combine.map_outputs_to_inputs`](https://github.com/mwouts/jupytext/blob/3a7bf840e57a96145792cf90bc969862c6582dca/jupytext/combine.py#L88), are at tested in [`test_combine.py`](https://github.com/mwouts/jupytext/blob/3a7bf840e57a96145792cf90bc969862c6582dca/tests/test_combine.py).
I have tested that
- an unchanged notebook does not see any change in its outputs
- an notebook with reordered cells has its outputs reordered
- a notebook in which cells are splitted sees the outputs going to the last chunck of the splitted cell
- and a notebook refactored has the outputs attributed according to the cell index.
This closes …
> New rules for combining inputs with outputs

- CHANGELOG.md
- jupytext/cell_reader.py
- jupytext/cell_to_text.py
- tests/test_active_cells.py
This PR reproduces the issue documented at #477
> Fix active cells in the py:percent format

- jupytext/cli.py
- jupytext/formats.py
- jupytext/jupytext.py
- jupytext/myst.py
I followed pylint's suggestions and
- fixed whitespaces issues
- moved imports at the top
- added docstrings
- and used more specific exception catching
@chrisjsewell , could you let me know if you're OK with this? I think we should double check the exception catching on `parser.parse` in `matches_mystnb` - can we really narrow it to `(TypeError, ValueError)` ?
> Increase pylint score to 9.78

- CHANGELOG.md
- tests/test_execute.py
> Skip the tests for `jupytext --execute` if a timeout occurs

- CHANGELOG.md
- docs/using-cli.md
> Use double quotes for long commands on Windows

- tests/test_read_simple_nomarker.py
- tests/test_read_simple_percent.py
This removes the last two warnings when running `pytest`.
> Catch expected warnings in the test suite

- jupytext/cli.py
- jupytext/paired_paths.py
- tests/test_cli.py
- tests/test_read_simple_markdown.py
Jupytext can be used to set format options on the command line (#130) with e.g. 
jupytext --opt split_at_heading=true notebook.Rmd
> Simplify format options on the CLI

- .pre-commit-config.yaml
This also uses the flake8 hook directly instead of the built in with
pre-commit-hooks.  The latter has deprecated the bundled flake8 hook.
Hence the change to the upstream one.
---
The [release](https://github.com/pre-commit/pre-commit-hooks/releases/tag/v3.0.0) that changes the `flake8` hook.
I hope this looks okay.
---
They all install just fine.
```
❯ pre-commit install --install-hooks
pre-commit installed at .git/hooks/pre-commit
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://gitlab.com/pycqa/flake8.
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused. …
```
> Update pre-commit to v3.1.0

- jupyter-config/nbconfig/notebook.d/jupytext.json
- jupytext/contentsmanager.py
- jupytext/version.py
- tests/test_contentsmanager.py
- The notebook extension is activated by default
- `new_untitled` works with the default extensions (`""` and `".ipynb"`)
Closes #443
> Fix new text notebook

- jupytext/config.py
- jupytext/paired_paths.py
- tests/test_cli.py
- tests/test_paired_paths.py
- tests/test_pre_commit.py
- Notebook pairings are bounded by the config directory
- Fixed paired notebooks in trees when the notebook is right under the notebook folder
> Root prefix not above config

- jupytext/languages.py
- tests/notebooks/ipynb_coconut/coconut_homepage_demo.ipynb
- tests/notebooks/mirror/ipynb_to_Rmd/coconut_homepage_demo.Rmd
- tests/notebooks/mirror/ipynb_to_hydrogen/coconut_homepage_demo.coco
- tests/notebooks/mirror/ipynb_to_md/coconut_homepage_demo.md
- tests/notebooks/mirror/ipynb_to_myst/coconut_homepage_demo.md
- tests/notebooks/mirror/ipynb_to_percent/coconut_homepage_demo.coco
- tests/notebooks/mirror/ipynb_to_script/coconut_homepage_demo.coco
After this [jupyter-related issue](https://github.com/evhub/coconut/issues/540), Coconut has up-to-date and easy-to-use interactions with the jupyter kernel. 
I've set up the test notebook to mimic the [home-page](http://coconut-lang.org) of the project, though examples that require extra definitions have been commented out. 
- Tests were successful: `2441 passed, 2 skipped in 40.37s`
-  pre-commit hooks successful: 
``` 
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://gitlab.com/pycqa/flake8.
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may …
```
> Add Coconut language

- tests/test_cli.py
- tests/test_execute.py
In some instances the timeout message appears on stderr #489
> Catch timeout messages both in the logs and in stderr #489

- .github/workflows/continuous-integration-conda.yml
- CHANGELOG.md
- MANIFEST.in
- environment-ci.yml
- jupytext/version.py
Code coverage is higher on the conda CI than on the pip CI, as more of Jupytext's optional dependencies are available (pandoc, myst-parser, sphinx-gallery). This PR fixes the coverage upload by adding `coverage` as an explicit dependency for the conda workflow (and deactivates Python 2.7 due to an error when executing Jupyter notebooks).
> Upload coverage from the conda CI workflow

- CHANGELOG.md
- requirements.txt
- setup.py
TOML is the default format for Jupytext configuration files (`.jupytext`, `.jupytext.toml` or `jupytext.toml`).
> Add toml as an explicit dependency

- .github/workflows/continuous-integration-conda.yml
We fix the "ImportError: No module named functools_lru_cache" when running Jupyter commands in Python 2.7 at e.g. https://github.com/mwouts/jupytext/runs/793874319 with
```
conda install backports.functools_lru_cache
```
> Restore Python 2.7 on the Conda CI

- tests/test_cli.py
- tests/test_paired_paths.py
In versions prior to 1.5.0, Jupytext had issue with `..` in paired formats. Here we had two tests that should be able to catch the issue documented at #564 .
> Reproduce the conditions for #564

- .codecov.yml
- .github/workflows/codeql-analysis.yml
- CHANGELOG.md
- codecov.yml
This PR improves the configuration of codecov:
- no notifications should be send before all jobs finish running
- target coverage for patches is 80%
- no alert should be triggered when coverage decreases by less than 0.2%
It also activates the new code scanning feature by GitHub
> Configure codecov, set up code scanning

- CHANGELOG.md
- README.md
- codecov.yml
- tests/test_cli.py
- tests/test_combine.py
- tests/test_execute.py
- tests/test_pep8.py
- tests/utils.py
- Skip the tests that execute a notebook on Windows to avoid timeout issues (close #489)
- Target 100% coverage in tests
> Skip the tests that execute notebooks on Windows

- CHANGELOG.md
- jupytext/cell_reader.py
- jupytext/cell_to_text.py
- jupytext/version.py
- tests/test_read_simple_percent.py
Code cell markers in the `percent` format have the same indentation as the first line of code in the cell.
Closes #562
> Indented markers percent

- CHANGELOG.md
- docs/config.md
- jupytext/cli.py
- jupytext/config.py
- jupytext/formats.py
- jupytext/header.py
- tests/test_cli_config.py
- tests/test_header.py
- tests/test_read_simple_markdown.py
This PR introduces the `hide_notebook_metadata` option for the Markdown format.
Closes #527 .
> Hide notebook metadata

- .github/workflows/continuous-integration-conda.yml
- CHANGELOG.md
- setup.py
> pip install jupytext[myst] should install myst-parser==0.8.x

- CHANGELOG.md
- jupytext/cli.py
- jupytext/formats.py
- jupytext/myst.py
- jupytext/pandoc.py
- tests/test_ipynb_to_myst.py
- tests/test_read_simple_pandoc.py
- tests/utils.py
With this PR, the `md:myst` and `md:pandoc` are always included in the Jupytext formats, and an informative runtime
error will occur if the required dependencies, resp. `myst-parser` and `pandoc`, are not installed. (#556)
For instance, if I don't have `myst-parser`, `jupytext README.md --to md:myst` results into
```bash
[jupytext] Reading README.md in format md
[jupytext] Writing README.md in format md:myst (destination file replaced)
(...)
ImportError: The MyST Markdown format requires 'myst_parser>=0.8'. Install it with e.g. 'pip install jupytext[myst]'
```
A [similar error message](https://user-images.githubusercontent.com/29915202/88977741-bb869500-d2be-11ea-947e-ce779c05253b.png) is displayed in Jupyter Notebook or Lab user if they opens a myst file without having installed `myst`. …
> Informative runtime error if myst is not installed

- CHANGELOG.md
- jupytext/cli.py
- tests/test_cli.py
`jupytext notebook.ipynb --to filename.py` will warn that `--to` is used in place of `--output`.
> Jupytext --to file warning

- CHANGELOG.md
- jupytext/contentsmanager.py
- tests/test_contentsmanager.py
> Warn if 'Include Metadata' is off when saving text files in Jupyter

- CHANGELOG.md
- setup.py
Following the [discussion in PR #590](https://github.com/mwouts/jupytext/pull/590#issuecomment-681623137), use the compatible release syntax (`~=`) to require a version of `myst-parser` in the `v0.8.X` range for the `myst` extra.
Additionally, remove the note in the `CHANGELOG`, as it is no longer relevant.
The changes from PR #590 for Conda
https://github.com/mwouts/jupytext/blob/5f292f2dc08cca074ae5a7eaae9ad3600b5c41b9/.github/workflows/continuous-integration-conda.yml#L68-L69
are left as they are, as there is no equivalent syntax in Conda.
---
**Short notes to save people in the future from reading the above mentioned discussion:**
In [PEP 440's "Compatible release" section](https://www.python.org/dev/peps/pep-0440/#compatible-release)
> For a given release identifier V.N, the …
> Use compatible release syntax for myst extra

- .github/workflows/continuous-integration-conda.yml
- CHANGELOG.md
- jupytext/myst.py
- requirements.txt
- setup.py
This is an alternative to #599 which has the dependency on `markdown-it-py` only when Python >= 3.6.
> Jupytext depends on markdownitpy

- CHANGELOG.md
- jupytext/config.py
- jupytext/formats.py
- jupytext/header.py
- jupytext/jupytext.py
- tests/test_read_simple_rmd.py
New option `root_level_metadata_as_raw_cell`. Set it to `False` if you don't want to see root level metadata of R Markdown notebooks as a raw cell in Jupyter.
Closes #415.
> New option root_level_metadata_as_raw_cell

- CHANGELOG.md
- tests/test_metadata_filters_from_config.py
> Test that metadata filters in the configuration files are taken into account when using `jupytext --to`

- CHANGELOG.md
- jupytext/cli.py
- tests/test_cli.py
> suggest to use `--sync` instead of `--set-formats` when argument is a file name

- CHANGELOG.md
- binder/postBuild
The mybinder build was failing at the command `jupyterlab build` with an advice to use `dev-build=False` and `minimize=False`.
With these new arguments the problem disappears.
> Fix jupyterlab build

- CHANGELOG.md
- jupytext/cli.py
- tests/test_execute.py
> New argument `--run-path`

- .github/workflows/continuous-integration-conda.yml
- .github/workflows/continuous-integration-pip.yml
- CHANGELOG.md
- environment.yml
- jupytext/version.py
- requirements-dev.txt
- setup.py
> Freeze optional dependency on `sphinx-gallery` to version `~=0.7.0`

- .gitignore
- jupytext/contentsmanager.py
Fixes the bug mentioned in https://github.com/mwouts/jupytext/pull/634#issuecomment-699834971. Previously, the monkey patch here:
https://github.com/mwouts/jupytext/blob/aea84d9850fe24a71fe871064ffb0646f5a44eb4/jupytext/contentsmanager.py#L172-L173
called the parent `save` method, which would [then call `nbformat.from_dict`](https://github.com/jupyter/notebook/blob/09ba565c96619d2150448bb0f4392004decc1014/notebook/services/contents/filemanager.py#L473-L479):
```python
if model['type'] == 'notebook':
nb = nbformat.from_dict(model['content'])
self.check_and_sign(nb, path)
self._save_notebook(os_path, nb)
if not self.checkpoints.list_checkpoints(path):
self.create_checkpoint(path)
```
before eventually calling `jupytext.writes` (via the patched `nbformat.writes`) as part of the …
> Fixes #634 bug: no `metadata` attribute

- .gitignore
- jupytext/contentsmanager.py
- setup.cfg
- tests/test_cli.py
- tests/test_cm_config.py
- tests/test_contentsmanager.py
- tests/test_escape_magics.py
- tests/test_read_simple_percent.py
- tests/test_save_multiple.py
- tests/test_trust_notebook.py
- tests/utils.py
With this PR we stop using `mock` to replace the `nbformat.reads` and `writes` functions with Jupytext's ones. Instead we use the parent contents manager to load/write the text files and parse them with Jupytext.
As a side effect, we don't use any more private methods from the `FileContentsManager` or `LargeFileManager`, and Jupytext can work on top of other contents managers like Jupyter-FS.
This is a follow-up on #621 and will hopefully close #618
> Jupytext's CM uses parent CM's get and save methods to read text files

- jupytext/languages.py
Add [Cython](https://cython.readthedocs.io/en/latest/src/quickstart/build.html#using-the-jupyter-notebook) to the list of language magics, so that Cython cells get commented out in non-notebook formats.
FWIW I don't think it would make sense to open Cython files as notebooks; each Cython cell in a notebook is compiled separately, so a file with any dependencies between cells would fail as a notebook.
> Add Cython to list of language magics

- jupytext/contentsmanager.py
& log the details of the error in the console
> All errors raised by Jupytext's CM are HTTP 500 (Internal Server)

- CHANGELOG.md
- tests/test_contentsmanager.py
> Jupytext tests work on non-English locales

- README.md
- docs/index.md
Add screenshots on how to open text notebooks in Jupyter Notebook & Lab to both the `README.md` and the documentation index.
> How to open a text notebook

- CHANGELOG.md
- environment-ci.yml
- environment.yml
- jupytext/cell_metadata.py
- jupytext/metadata_filter.py
- tests/notebooks/mirror/ipynb_to_pandoc/julia_benchmark_plotly_barchart.md
- tests/test_metadata_filter.py
And fix the issue documented at #656 - the global configuration was uneffective on cell metadata present in the text file.
> Filter out the execution cell metadata by default

- jupytext/jupytext.py
writes returns a string, and does not operate on a file object.
Can't say this enough - but I use this module so much that it's difficult to
imagine life without it.  Thanks again for all your work.
> DOC: fix writes function docstring

- .github/workflows/continuous-integration-pip.yml
- CHANGELOG.md
- jupytext/cli.py
- jupytext/kernels.py
- tests/utils.py
The `--set-kernel -` command, on a Python notebook, now gives an explicit error when no kernel is not found that matches the current Python executable (instead of using the default Python kernel as was the case previously).
> The --set-kernel - command fails when no Python kernel matches the current Python executable

- CHANGELOG.md
- jupytext/cli.py
- jupytext/combine.py
- jupytext/compare.py
- jupytext/pairs.py
- jupytext/version.py
- tests/test_combine.py
- tests/test_mirror.py
- tests/test_read_simple_markdown.py
- tests/test_read_simple_nomarker.py
- it now returns the combined notebook (rather than modifying in place the source notebook)
- the output cell is used as the basis for the new cell, in order to preserve additional attributes like 'attachments'
Closes #671
> Revisit the function combine_inputs_with_outputs

- .github/workflows/continuous-integration.yml
(because they are skipped by skip-duplicate when a tag is added)
> Remove dependencies on the Publish step

- docs/CHANGELOG.md
- jupytext/contentsmanager.py
- jupytext/version.py
- tests/test_contentsmanager.py
> Text notebooks have the same format and mimetype as ipynb notebooks

- LICENSE
- docs/CHANGELOG.md
- environment.yml
- jupytext/version.py
- requirements.txt
- setup.py
The plan is to deliver a version of Jupytext (version 1.8.1) that will be identified by pypi.org as the last version compatible with Python 2.7 and 3.5, see #697
> The dependency on `markdown-it-py` is conditional on `python>=3.6`

- docs/CHANGELOG.md
- environment.yml
- jupytext/version.py
- requirements.txt
- setup.py
Add an explicit dependency to fix #697
> Jupytext 1.8.2 depends on `python>=3.6`

- .github/workflows/continuous-integration.yml
- .gitignore
- MANIFEST.in
- install.json
- jupytext/__init__.py
- packages/labextension/package.json
- pyproject.toml
- requirements-dev.txt
- setup.py
Add support for JupyterLab 3 extension system
> JupyterLab 3 update

- jupytext/version.py
- setup.py
> Don't build the jupyterlab-jupytext extension if npm is not available

- .github/workflows/continuous-integration.yml
- setup.py
Follow-up on #706 - with this we gain a few minutes on the CI (13 min instead of 17 min)
> Use BUILD_JUPYTERLAB_EXTENSION in the PyPi-publish step

- .github/workflows/continuous-integration.yml
- docs/CHANGELOG.md
- environment-ci.yml
- environment.yml
- requirements.txt
Jupytext does not work well with the new cell ids yet - see #715
> At the moment Jupytext requires nbformat<=5.0.8

- docs/CHANGELOG.md
- jupytext/magics.py
- tests/test_escape_magics.py
> Python magic commands may be indented

- docs/CHANGELOG.md
- tests/test_pep8.py
With this PR we add the test suggested at #682
> Test that `py:percent` scripts end with exactly one blank line

- docs/CHANGELOG.md
- docs/config.md
- tests/test_cm_config.py
As reported at #696, Jupytext can't work with symbolic links to files, because Jupyter has a wrong timestamp for them.
With this PR we add a test to make sure that it works well with symbolic links to folders.
Closes #696.
> Test that Jupytext works well with symbolic links to folders

- docs/CHANGELOG.md
- jupytext/jupytext.py
- tests/test_cli.py
- tests/test_nbformat_version.py
In this PR we add checks to make sure that Jupytext is used on notebook in versions of nbformat with which it has been tested. See for instance #681 and #715.
> Check nbformat version

- docs/CHANGELOG.md
- jupytext/cell_reader.py
- jupytext/cell_to_text.py
- jupytext/formats.py
- jupytext/myst.py
- jupytext/version.py
- tests/test_markdown_in_code_cells.py
- tests/test_read_simple_markdown.py
This PR will close #712 .
@rsokl I am considering taking this opportunity to remove the parsing of Python strings inside code cells (since now the cell marker is non-ambiguous), but that may break some of your notebooks, cf. #419 . Do you have many of them?
Also @chrisjsewell I have not yet ported this to `md:myst` but I intend to do so before merging.
> Encapsulate code cells with triple backticks with +1 backtick in Markdown

- docs/CHANGELOG.md
- docs/languages.md
- jupytext/formats.py
- jupytext/languages.py
- tests/notebooks/ipynb_sage/sage_print_hello.ipynb
- tests/notebooks/mirror/ipynb_to_Rmd/sage_print_hello.Rmd
- tests/notebooks/mirror/ipynb_to_hydrogen/sage_print_hello.sage
- tests/notebooks/mirror/ipynb_to_md/sage_print_hello.md
- tests/notebooks/mirror/ipynb_to_myst/sage_print_hello.md
- tests/notebooks/mirror/ipynb_to_percent/sage_print_hello.sage
- tests/notebooks/mirror/ipynb_to_script/sage_print_hello.sage
- tests/test_auto_ext.py
> Support Sage notebooks

- jupytext/cli.py
This add the Recursive option which is [supported since version 3.5](https://docs.python.org/3.6/library/glob.html). That way we can use cli with `**/` pattern.
> feat: add recursive glob option

- docs/CHANGELOG.md
- tests/test_cli.py
We test that `jupytext [...] **/*.py` has the expected effect (see #731)
> Add a test for the recursive glob pattern

- jupytext/__main__.py
- tests/test_cli.py
Allows e.g.
```
python -m jupytext my_notebook.ipynb --to Rmd
```
I _think_ this is the correct way to do this, but I don't personally
have much experience with this machinery.
> Add __main__ to allow calling via python -m

- .github/workflows/continuous-integration.yml
- docs/CHANGELOG.md
- environment-ci.yml
- environment.yml
- jupytext/cli.py
- jupytext/compare.py
- jupytext/jupytext.py
- requirements-dev.txt
- requirements.txt
- setup.py
- tests/test_active_cells.py
- tests/test_black.py
- tests/test_cli.py
- tests/test_cm_config.py
- tests/test_compare.py
- tests/test_contentsmanager.py
- tests/test_mirror.py
- tests/test_nbformat_version.py
- tests/test_pre_commit_0_ipynb_to_py.py
- tests/test_pre_commit_5_reformat_markdown.py
- tests/test_pre_commit_scripts.py
- tests/test_preserve_empty_cells.py
- tests/test_read_simple_markdown.py
- tests/test_read_simple_percent.py
- tests/test_read_simple_python.py
- tests/test_read_simple_rmd.py
- tests/test_read_write_functions.py
Jupytext preserves the cell id if one uses either `--update` or `--sync` (since `jupytext>=1.7.1`).
This PR adapts the tests to account for the possible differences in cell ids when cells are generated independently from the notebook being tested.
Will close #734 and #735
> Test Jupytext with notebooks in version 4.5 (nbformat>=5.1.0)

- docs/CHANGELOG.md
- tests/conftest.py
- tests/test_cell_id.py
> Use non-random cell ids in tests

- jupytext/cli.py
- jupytext/combine.py
- jupytext/config.py
- jupytext/contentsmanager.py
- jupytext/header.py
- jupytext/jupytext.py
- jupytext/version.py
- tests/test_contentsmanager.py
- tests/test_header.py
- tests/test_metadata_filters_from_config.py
- tests/test_pre_commit_mode.py
This PR adds a `config` argument to the `jupytext.read(s)` and `jupytext.write(s)` functions.
This should help fixing #752 
What remains to be done:
> Use config in read and write functions

- jupytext/jupytext.py
The docstring and code act like it is optional, but the function
signature is not optional.
> Mark fmt as optional in reads

- .pre-commit-config.yaml
- docs/CHANGELOG.md
- environment.yml
- jupytext/cli.py
- jupytext/config.py
- jupytext/contentsmanager.py
> Use an explicit encoding="utf-8" in every call to open

- docs/CHANGELOG.md
- jupytext/metadata_filter.py
- tests/test_black.py
- tests/test_cli.py
> Cell metadata that is specific to text files must come from these files, not ipynb

- docs/CHANGELOG.md
- jupytext/cli.py
- jupytext/config.py
- tests/test_cli.py
With this change we won't update the timestamp of source files when the destination file is not in the pair.
As a reminder, the reason why we need to update the timestamp is #335
Fixes #765 and #767
> Do not update source file timestamp when not required

- docs/faq.md
- backslashes to slashes in paths
- capitalisation
- code blocks
> Improve formatting in faq

- docs/CHANGELOG.md
- jupytext/cli.py
- tests/test_cli.py
> New option --use-source-timestamp

- docs/CHANGELOG.md
- jupytext/cli.py
- jupytext/magics.py
- tests/test_escape_magics.py
Variables created with magic commands like e.g.
```
result = %sql SELECT * FROM quickdemo WHERE value > 25
```
should be commented out in the `.py` representation.
Cf. #781
> Comment variables created from magic commands

- docs/CHANGELOG.md
- jupytext/cli.py
- tests/test_black.py
> The `--warn-only` option also applies to pipes

- docs/languages.md
When I click the link, it returns 404 because it looks like the contributing.md was in the main folder (and, by the way, was uppercase and now it is not) and now is in the docs/ folder.
> Update contributing.md link

- docs/CHANGELOG.md
- docs/formats.md
- jupytext/version.py
- tests/test_read_simple_percent.py
(than on the contents manager)
Closes #809
> The cell_markers option are more conveniently set in the jupytext config file

- docs/CHANGELOG.md
- tests/test_pre_commit_0_ipynb_to_py.py
- tests/test_pre_commit_1_sync.py
- tests/test_pre_commit_2_sync_nbstripout.py
- tests/test_pre_commit_3_sync_black_nbstripout.py
- tests/test_pre_commit_4_sync_execute.py
- tests/test_pre_commit_5_reformat_markdown.py
- tests/utils.py
> Skip the pre-commit tests when the Jupytext folder is not a git repo

- jupytext/cell_reader.py
The tests don't pass when a more recent version of `sphinx_gallery` is installed, cf. #814
> The rst2md option requires sphinx_gallery<=0.7.0

- jupytext/pandoc.py
- tests/utils.py
As the mirror files changed slightly when Pandoc 2.11 was introduced
https://github.com/mwouts/jupytext/commit/c07d919702999056ce47f92b74f63a15c8361c5d
Relates to #814
> Require Pandoc >= 2.11 in the tests

- docs/CHANGELOG.md
- jupytext/paired_paths.py
- tests/test_black.py
- tests/test_cli.py
- tests/test_paired_paths.py
> Reproduce and fix the issue with notebooks paired with scripts in a folder

- docs/CHANGELOG.md
- jupytext/magics.py
- tests/test_escape_magics.py
This is a quick regexp implementation for #816
> System assigns of the form `var = !cmd` are commented out

- docs/CHANGELOG.md
- jupytext/cli.py
- tests/test_black.py
In Jupytext 1.11.3 the logs for `jupytext --pipe black test.ipynb` are
```
[jupytext] Reading test.ipynb in format ipynb
[jupytext] Executing black -
[jupytext] Writing test.ipynb (destination file replaced [use --update to preserve cell outputs and ids])
```
which wrongly suggest that outputs are lost.
This PR changes the log to just
```
[jupytext] Reading test.ipynb in format ipynb
[jupytext] Executing black -
[jupytext] Writing test.ipynb
```
> Remove the mention of '--update' in 'jupytext --pipe' since outputs are preserved already

- environment.yml
- jupytext/contentsmanager.py
- tests/test_trust_notebook.py
This PR adds a test that a simple notebook can be trusted #797 .
Most of the problem with notebooks that cannot be trusted comes from using Jupyter Lab in a version prior to 3.0.13, in which cell ids were not available, so we recommend using a newer version for developing.
> Test that notebooks can be trusted (2)

- docs/config.md
- jupytext/config.py
- jupytext/contentsmanager.py
- tests/test_cm_config.py
- tests/test_config.py
Resolves #828.
It's slightly annoying that it's necessary to open the `pyproject.toml` document twice - first to check if it has a valid `[tool.jupytext]` table in `find_jupytext_configuration_file`, and then again to parse it properly in `parse_jupytext_configuration_file`, but I think that rewriting this code to enable a single read would be significantly more complicated, and a rather premature optimisation.
Happy to take comments - hopefully the documentation changes read clearly enough.
And once this is done, I'll open a PR [here](https://github.com/carlosperate/awesome-pyproject) for you :)
> Implement support for configuration via pyproject.toml

- docs/CHANGELOG.md
- docs/config.md
- jupytext/config.py
- jupytext/contentsmanager.py
With this PR we resolve the three comments at #830
> Follow up on #830

- .github/workflows/continuous-integration.yml
- README.md
- docs/CHANGELOG.md
- docs/formats.md
- docs/index.md
- jupytext/compare.py
- jupytext/formats.py
- jupytext/jupytext.py
- jupytext/nbextension/index.js
- jupytext/quarto.py
- packages/labextension/CHANGELOG.md
- packages/labextension/package.json
- packages/labextension/src/index.ts
- tests/notebooks/mirror/ipynb_to_quarto/Notebook_with_R_magic.qmd
- tests/notebooks/mirror/ipynb_to_quarto/Notebook_with_more_R_magic_111.qmd
- tests/notebooks/mirror/ipynb_to_quarto/cat_variable.qmd
- tests/notebooks/mirror/ipynb_to_quarto/frozen_cell.qmd
- tests/notebooks/mirror/ipynb_to_quarto/julia_benchmark_plotly_barchart.qmd
- tests/notebooks/mirror/ipynb_to_quarto/jupyter.qmd
- tests/notebooks/mirror/ipynb_to_quarto/jupyter_again.qmd
- tests/test_contentsmanager.py
- tests/test_mirror.py
- tests/test_read_simple_quarto.py
- tests/utils.py
> Add the Quarto format (.qmd files) to Jupytext

- tests/test_black.py
I hit this test failure in an environment where `black` was not installed. The other tests were skipped, but this last one was missing the `@requires_black` decorator.
> Mark a test as requiring black

- docs/CHANGELOG.md
- jupytext/cell_reader.py
- jupytext/cell_to_text.py
- jupytext/version.py
- tests/notebooks/mirror/ipynb_to_percent/Line_breaks_in_LateX_305.py
- tests/test_cli.py
- tests/test_raw_strings.py
> Encode Markdown cells with a backslash as raw strings in py:percent scripts

- tests/test_cell_markers.py
> More tests on cell markers

- docs/CHANGELOG.md
- jupytext/contentsmanager.py
> Do not reload the Jupytext config file unless a notebook is opened/saved

- jupytext/quarto.py
> Display the errors raised by 'quarto'

- README.md
- binder/labconfig/default_setting_overrides.json
- docs/CHANGELOG.md
- docs/index.md
- jupytext/version.py
- packages/labextension/CHANGELOG.md
- packages/labextension/package.json
- packages/labextension/src/index.ts
> The "Jupytext Notebook" viewer works for more notebook extensions

- environment.yml
- requirements.txt
This implements some internal changes, but won't affect jupytext
(see https://github.com/executablebooks/markdown-it-py/releases/tag/v2.0.0)
> Allow for markdown-it-py v2.0

- tests/test_cli_check.py
With this PR I am trying to reproduce #878 with a test
> Test that '--checks' accepts notebooks either before or after the check command

- README.md
- binder/postBuild
- docs/CHANGELOG.md
- jupytext/header.py
- jupytext/version.py
- tests/test_doc_files_are_notebooks.py
- tests/test_read_empty_text_notebook.py
The purpose of this PR is to document how to open links to .md files in notebooks as notebooks (will close #271)
A requirement is `jupyterlab>=4.0.0a16`, which I have added to Binder with this PR.
It might be the only one - at least, if I open the README.md at https://mybinder.org/v2/gh/mwouts/jupytext/open_md_links_as_notebooks_271 then the links seem to all open with the notebook viewer !
I am not 100% sure that anchors like `[MyST Markdown](docs/formats.md#myst-markdown)` work, but anyway in this example the rendering of the `formats.md` file as a notebook is not great - I'll investigate
> Open md links as notebooks (doc + Binder)

- README.md
- binder/postBuild
- binder/requirements.txt
- docs/CHANGELOG.md
- docs/config.md
- docs/examples.md
- docs/faq.md
- docs/formats.md
- docs/index.md
- docs/paired-notebooks.md
- docs/using-cli.md
- packages/labextension/CHANGELOG.md
- packages/labextension/README.md
Continuation of #889
Fix #271
TODO
> Open links to md files as Notebooks in Jupyter Lab

- docs/CHANGELOG.md
- pyproject.toml
- tests/test_cli.py
- tests/test_cm_config.py
- tests/test_pre_commit_scripts.py
> Filter known warnings in tests and raise on others

- docs/CHANGELOG.md
- jupytext/contentsmanager.py
- jupytext/version.py
- tests/invalid_file_896.md
- tests/test_invalid_file.py
> Jupytext refuses to open a non-unicode file (api, cli & jupyter)

- LICENSE
- docs/CHANGELOG.md
- jupytext/cli.py
- jupytext/contentsmanager.py
- jupytext/jupytext.py
- jupytext/version.py
- tests/test_cm_config.py
- tests/test_pre_commit_1_sync_with_config.py
> Filter the text_representation metadata in the contents manager

- docs/languages.md
- jupytext/languages.py
- tests/notebooks/ipynb_haskell/haskell_notebook.ipynb
- tests/notebooks/mirror/ipynb_to_Rmd/haskell_notebook.Rmd
- tests/notebooks/mirror/ipynb_to_hydrogen/haskell_notebook.hs
- tests/notebooks/mirror/ipynb_to_md/haskell_notebook.md
- tests/notebooks/mirror/ipynb_to_myst/haskell_notebook.md
- tests/notebooks/mirror/ipynb_to_percent/haskell_notebook.hs
- tests/notebooks/mirror/ipynb_to_script/haskell_notebook.hs
Haskell has been added as a supported language. Example notebook has been added.
Tests executed: 
- pytest was run and mirror tests pass. 
- Package was built locally and installed. It is possible to pair a Jupyter notebook running a Haskell kernel with a script; basic functionality has been tested (e.g. opening and editing script, checking to see if changes are reflected in notebook and vice versa).
> Added Haskell as a supported language. 

- docs/CHANGELOG.md
- jupytext/cli.py
- jupytext/jupytext.py
- tests/test_execute.py
> Fix `cat notebook.md | jupytext --execute`

- docs/CHANGELOG.md
- jupytext/header.py
- tests/test_remove_encoding.py
- tests/test_unicode.py
> Don't force an UTF encoding for non-ascii Python notebooks

- docs/languages.md
- jupytext/languages.py
- tests/notebooks/ipynb_tcl/tcl_test.ipynb
- tests/notebooks/mirror/ipynb_to_Rmd/tcl_test.Rmd
- tests/notebooks/mirror/ipynb_to_hydrogen/tcl_test.tcl
- tests/notebooks/mirror/ipynb_to_md/tcl_test.md
- tests/notebooks/mirror/ipynb_to_myst/tcl_test.md
- tests/notebooks/mirror/ipynb_to_percent/tcl_test.tcl
- tests/notebooks/mirror/ipynb_to_script/tcl_test.tcl
- update languages.py.
- update docs/languages.md
- add tests/notebooks/ipynb_tcl
pytest results: 1 failed, 2592 passed, 147 skipped, 1 xfailed, 4 warnings
```
================================== FAILURES ===================================
_ test_identity_source_write_read[.\\jupytext\\t
ests\\.\\test_pre_commit_scripts.py] _
py_file = '.\\jupytext\\tests\\.\\test_pre_commi
t_scripts.py'
@pytest.mark.parametrize(
"py_file",
[
py_file
for py_file in list_notebooks("../jupytext") + list_notebooks(".")
if py_file.endswith(".py")
if "folding_markers" not in py_file
],
)
def test_identity_source_write_read(py_file):
with open(py_file) as fp:
>           py = fp.read()
E           UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 924
6: illegal multibyte sequence …
```
> add Tcl as a supported language

- setup.py
Heya, I already did this in #885, but missed out updating this file.
When is `requirements.txt` actually used, as opposed to `install_requires`?
> Allow for markdown-it-py v2

- README.md
This PR proposes to add a "launch on [renku](https://renkulab.io/)" badge to the README.
Like binder, renku provides interactive jupyter sessions for user to try notebooks and code examples.
In addition, renku sessions are tied to a gitlab repository, which logged in users can fork to modify the code and save their changes.
The badge starts a session from a [renku gitlab repository](https://renkulab.io/projects/best-practices/jupytext). When a session is started, it builds a docker image from the repository and gives you access to a jupyterlab interface. 
For this particular example, I have setup a gitlab repository which imports this repository as a git submodule. A Gitlab CI schedule  executed every week updates the submodule. In addition, a post-init hook automatically pulls demo …
> Add "launch on renku" badge in README

- .pre-commit-config.yaml
- docs/CHANGELOG.md
- docs/using-pre-commit.md
- tests/test_pre_commit_2_sync_nbstripout.py
- tests/test_pre_commit_3_sync_black_nbstripout.py
- tests/test_pre_commit_5_reformat_markdown.py
The CI is failing on the test `test_pre_commit_hook_sync_black_nbstripout`, see also #940 and #942
I cannot reproduce that error locally, so I am trying to update the hooks used by this test.
The details for the error are below:
```
@skip_pre_commit_tests_on_windows
@skip_pre_commit_tests_when_jupytext_folder_is_not_a_git_repo
def test_pre_commit_hook_sync_black_nbstripout(
tmpdir,
cwd_tmpdir,
tmp_repo,
jupytext_repo_root,
jupytext_repo_rev,
notebook_with_outputs,
):
"""Here we sync the ipynb notebook with a py:percent file and also apply black and nbstripout."""
pre_commit_config_yaml = f"""
repos:
- repo: {jupytext_repo_root}
rev: {jupytext_repo_rev}
hooks:
- id: jupytext
args: [--sync, --pipe, black]
additional_dependencies:
- black==20.8b1  # Matches hook
- repo: …
```
> Update the hooks used in the documentation and tests

- docs/CHANGELOG.md
- jupytext/contentsmanager.py
- tests/test_trust_notebook.py
(as they don't include any output cells)
Fixes #941
> Text-only notebooks are always trusted

- tests/test_cli.py
The exception/warning does not seem to occur any more on the CI, so the "continue" instruction is not covered.
Rather than dismissing the exception for this warning, I prefer to ignore the "continue" line in the coverage.
> Ignore non-coverage of (gone) exception

- docs/CHANGELOG.md
- jupytext/config.py
- jupytext/contentsmanager.py
- tests/conftest.py
- tests/test_cm_config.py
The default value for the new option is 'info_if_changed' to reduce the number of lines logged by the contents manager.
Closes #959
> New config option `cm_config_log_level`

- docs/CHANGELOG.md
- jupytext/cli.py
- tests/conftest.py
- tests/test_cli.py
> Do not override test.ipynb when doing 'jupytext --set-formats' on test.py

- docs/CHANGELOG.md
- jupytext/cli.py
- tests/conftest.py
- tests/test_cli.py
- tests/test_pre_commit_1_sync_with_no_config.py
The test works without filtering on `.ipynb` files thanks to the resolution of #969 that has been integrated in this branch.
Closes #967 .
> Add a new test that documents how to use the pre-commit hook with '--set-formats'

- docs/using-cli.md
> Add notes on error-tolerant execution to CLI docs

- docs/CHANGELOG.md
- tests/test_cli.py
Document how to use the folder & prefix matching for #974
> Add a test to document how to use the folder & prefix matching

- .github/workflows/continuous-integration.yml
- .pre-commit-config.yaml
- codecov.yml
- docs/CHANGELOG.md
- jupytext/__init__.py
- jupytext/version.py
- tests/test_auto_ext.py
> Default to LargeFileManager when base class is async

- docs/languages.md
- jupytext/cell_metadata.py
- jupytext/languages.py
- tests/notebooks/ipynb_wolfram/wolfram.ipynb
- tests/notebooks/mirror/ipynb_to_Rmd/wolfram.Rmd
- tests/notebooks/mirror/ipynb_to_hydrogen/wolfram.wolfram
- tests/notebooks/mirror/ipynb_to_md/wolfram.md
- tests/notebooks/mirror/ipynb_to_myst/wolfram.md
- tests/notebooks/mirror/ipynb_to_percent/wolfram.wolfram
- tests/notebooks/mirror/ipynb_to_script/wolfram.wolfram
This adds support for Wolfram Language notebooks. For background, see:
https://github.com/WolframResearch/WolframLanguageForJupyter
Unfortunately, the way the Wolfram Language Jupyter kernel was designed poses a couple of issues with jupytext which I had to work around in this commit:
- The language_info name is "Wolfram Language", which has unusual capitalization and whitespace. jupytext is mostly fine with this, except for Rmd where I had to hack around it in the parser.
- The file extension is .m which clashes with Matlab. The current code structure seems to assume that an extension always maps to a single language. I worked around it by inventing a new extension (.wolfram), which is clearly not great but works fine for most use cases.
> Add support for Wolfram Language

- .github/workflows/continuous-integration.yml
- .pre-commit-config.yaml
- jupytext/cell_reader.py
- jupytext/compare.py
- jupytext/myst.py
- tests/test_combine.py
- tests/test_hide_remove_input_outputs_rmarkdown.py
- tests/test_read_simple_python.py
I saw that `jupytext`'s CI was broken so thought I'd try to help fix it. There's lots of cleaning that could be done on the CI, but this just gets it running again.
This updates all the GitHub Actions to their latest releases and updates and applies the pre-commit hooks so those pass as well. It additionally fixes the dependency conflicts happening by trying to install the linting dependencies for older Pythons by just having the lint job be separate as it only needs to run once, not for every Python being tested.
I also threw in the use of `python -m pip` pattern over just `pip` even though it isn't needed to try to spread this best practice to others who might be looking at jupytext's CI. Feel free to ask for that to be removed if you aren't a fan.
> fix: Get CI running again

- docs/languages.md
- jupytext/languages.py
- jupytext/magics.py
- tests/notebooks/ipynb_sas/sas.ipynb
- tests/notebooks/mirror/ipynb_to_Rmd/sas.Rmd
- tests/notebooks/mirror/ipynb_to_hydrogen/sas.sas
- tests/notebooks/mirror/ipynb_to_md/sas.md
- tests/notebooks/mirror/ipynb_to_myst/sas.md
- tests/notebooks/mirror/ipynb_to_percent/sas.sas
- tests/notebooks/mirror/ipynb_to_script/sas.sas
All test passing and verified that files are valid scripts.
> Adding SAS languague support

- docs/CHANGELOG.md
- jupytext/version.py
**Added**
- Added Stata as a supported language ([#1027](https://github.com/mwouts/jupytext/pull/1027)) - thanks to [Raffaele Mancuso](https://github.com/raffaem) for this contribution
- Added SAS as a supported language ([#1047](https://github.com/mwouts/jupytext/pull/1047)) - thanks to [lawrencet149](https://github.com/lawrencet149) for this contribution
- We have added a series of test to make sure that the main formats support cell tags ([#1024](https://github.com/mwouts/jupytext/issues/1024))
**Fixed**
- When a metadata key is not a valid identifier, a warning is emitted and the metadata is not saved to the text representation ([#1042](https://github.com/mwouts/jupytext/issues/1042))
- The CI was fixed by [Matthew Feickert](https://github.com/matthewfeickert) …
> Version 1.14.5

- binder/postBuild
With this PR we install a dev version of `nbclassic` that does not redirect text notebooks to `files/` (causing text notebooks to be downloaded rather than opened)
> Temporary workaround for #1051 on Binder

- docs/CHANGELOG.md
- jupytext/version.py
- packages/labextension/CHANGELOG.md
- packages/labextension/package.json
- pyproject.toml
This is the last version of the extension compatible with `jupyterlab==3.x`.
> Release jupyterlab-jupytext==1.3.9

- .github/workflows/continuous-integration.yml
- .github/workflows/publish.yml
- docs/CHANGELOG.md
- Run on push/pull requests onto main
- Use concurrency rather than skip_duplicate
- Remove old lint job since it has been superseded by pre-commit
- Simplify CodeQL
- Upload coverage with codecov/codecov-action@v3
- Use trusted publishing
> Reorganize the CI (attempt #2)

- docs/CHANGELOG.md
- jupytext/cell_reader.py
- jupytext/pandoc.py
- jupytext/parse_version.py
- jupytext/quarto.py
> Use either `pkg_resources` or `packaging` to parse version numbers

- .github/workflows/publish.yml
The name is currently `CI` which is incorrect
> Rename publish workflow

- jupytext/version.py
- packages/labextension/src/index.ts
a fix for solving issue #1107 
here's what both widgets (Notebook and Jupytext Notebook) look like
---
as can be seen on the screenshot there remains issues related to extensions
here I have installed `jupyterlab-courselevels` that adds some buttons in the toolbar; and what happens is that these buttons show up in the pure Notebook (ipynb) widget but not in the Jupytext Notebook widget
IMO this PR is still very welcome because
* the situation is far better than it was before this work
* I suspect that getting this to work perfectly is something very tricky
* especially considering that we build in a jlab3 environment, where some of the symbols that are, I think, needed to solve this properly, are not defined to typescript
So @mwouts I would be grateful if you could publish this under pypi …
> restore notebook toolbar under jlab4 - fix for issue #1107

- docs/CHANGELOG.md
- jupytext/contentsmanager.py
- tests/test_contentsmanager.py
> Ignore invalid pyproject.toml files in Jupytext's content manager

- demo/get_started.md
- docs/install.md
- docs/text-notebooks.md
- jupytext/jupytext_config.py
- jupytext/labconfig.py
- setup.py
with nb7 about to be released, the default versions of jupyterlab(4)/notebook(7) will both require to configure `defaultViewers` if one wants, for example, to easily open text notebooks from the web app, or to be able to open notebooks through a URL (these settings were not required with nbclassic)
here's a typical setup (this one is right for my use case, but more languages could be added of course)
```
cat ~/.jupyter/labconfig/default_setting_overrides.json
{
"@jupyterlab/docmanager-extension:plugin": {
"defaultViewers": {
"python": "Jupytext Notebook",
"markdown": "Jupytext Notebook"
}
}
}
```
So I've been thinking that providing a simple way to safely implement these settings would be helpful, especially for large classes of beginner students
Here's a POC for that
Of course it would …
> a helper tool for initializing defaultViewers in labconfig/

- packages/labextension/package.json
- packages/labextension/src/index.ts
- packages/labextension/yarn.lock
This PR:
- adds support for [jupyterlab-rise](https://github.com/jupyterlab-contrib/rise)
- clean some commented code
- fix setting metadata when modified for JupyterLab 4+
> FYI @parmentelat in JupyterLab 4, metadata obtained are a copy of the document metadata. So modifying them required to explicitly call `setMetadata` with the new value.
> Add support for RISE slides in JupyterLab

- .github/workflows/continuous-integration.yml
- docs/CHANGELOG.md
- jupytext/version.py
Plus, a workaround for #1127, we publish the build artifacts
> Version 1.15.2

- docs/languages.md
Haskell and Tcl were out of order in an otherwise sorted list. Sorted with:
```python
sorted(languages.splitlines(), key=str.lower)
```
> Alphabetize languages list

- pyproject.toml
We will from now on test Jupytext agains jupyter-fs<0.4.0, because the more recent versions provide an async contents manager, which is not supported by Jupytext at the moment.
Cf. #1150
> Use jupyter-fs<0.4.0 in tests

- docs/advanced-options.md
- docs/formats-scripts.md
- pyproject.toml
The source files have been moved from `jupytext` to `src/jupytext`, we need to update the documentation accordingly.
> Fix links to source files in the documentation

- .github/codecov.yml
- .github/workflows/ci.yml
- .github/workflows/step_tests-conda.yml
- .github/workflows/step_tests-pip.yml
- pyproject.toml
The objective is to close #1171 and #1172
> Restore the codecov comments on PRs

- src/jupytext_config/__main__.py
- src/jupytext_config/jupytext_config.py
- src/jupytext_config/labconfig.py
- tests/integration/jupytext_config/test_jupytext_config.py
- tests/unit/test_labconfig.py
> Move the jupytext-config helpers to a subpackage, and add tests

- .github/codecov.yml
- .github/workflows/step_tests-pip.yml
- CHANGELOG.md
- README.md
- jupyterlab/package.json
- jupyterlab/packages/jupyterlab-jupytext-extension/CHANGELOG.md
- jupyterlab/packages/jupyterlab-jupytext-extension/package.json
- jupyterlab/packages/jupyterlab-jupytext-extension/ui-tests/package.json
- pyproject.toml
- src/jupytext/version.py
- tests/integration/contents_manager/test_contentsmanager.py
In this PR we 
- bump the version number for the jupyterlab-jupytext extension to 1.4.1
- update the CHANGELOG.md
- and setup a new CI build that will test Jupytext and its extension against the pre-release versions of Python dependencies
> Version 1.16.0rc0

- .github/workflows/ci.yml
This is required to make the comments work on PRs coming from a fork
Cf. https://github.com/marketplace/actions/comment-pull-request:
> Note that, if the PR comes from a fork, it will have only read permission despite the permissions given in the action for the pull_request event. In this case, you may use the pull_request_target event. With this event, permissions can be given without issue (the difference is that it will execute the action from the target branch and not from the origin PR).
> Use pull_request_target event rather than pull_request

- src/jupytext/cell_reader.py
- tests/functional/simple_notebooks/test_read_simple_rmd.py
> Fix the handling of bibliography sections in R Markdown notebooks

- docs/using-pre-commit.md
I noticed the links to the pre-commit examples were outdated.
> Update links to pre-commit examples

- jupyterlab/packages/jupyterlab-jupytext-extension/src/commands.ts
The bug shows up when the user unpairs all the formats. It is reproducible in both notebook and JupyterLab.
Fixes #1191
> Ensure we set jupytext metadata to model

- .ci/environment-ci.yml
- .github/workflows/step_tests-conda.yml
- CHANGELOG.md
- environment.yml
- src/jupytext/jupytext.py
- tests/conftest.py
- tests/data/notebooks/outputs/ipynb_to_pandoc/Notebook_with_R_magic.md
- tests/data/notebooks/outputs/ipynb_to_pandoc/Notebook_with_more_R_magic_111.md
- tests/data/notebooks/outputs/ipynb_to_pandoc/cat_variable.md
- tests/data/notebooks/outputs/ipynb_to_pandoc/convert_to_py_then_test_with_update83.md
- tests/data/notebooks/outputs/ipynb_to_pandoc/frozen_cell.md
- tests/data/notebooks/outputs/ipynb_to_pandoc/ir_notebook.md
- tests/data/notebooks/outputs/ipynb_to_pandoc/julia_benchmark_plotly_barchart.md
- tests/data/notebooks/outputs/ipynb_to_pandoc/jupyter.md
- tests/data/notebooks/outputs/ipynb_to_pandoc/jupyter_again.md
- tests/data/notebooks/outputs/ipynb_to_pandoc/jupyter_with_raw_cell_in_body.md
- tests/data/notebooks/outputs/ipynb_to_pandoc/jupyter_with_raw_cell_on_top.md
- tests/data/notebooks/outputs/ipynb_to_pandoc/notebook_with_complex_metadata.md
- tests/data/notebooks/outputs/ipynb_to_pandoc/nteract_with_parameter.md
- tests/data/notebooks/outputs/ipynb_to_pandoc/plotly_graphs.md
- tests/data/notebooks/outputs/ipynb_to_pandoc/sample_rise_notebook_66.md
- tests/data/notebooks/outputs/ipynb_to_pandoc/text_outputs_and_images.md
- tests/external/pre_commit/test_pre_commit_scripts.py
- tests/external/simple_external_notebooks/test_read_simple_pandoc.py
- tests/functional/cli/test_cli.py
- tests/unit/test_cell_id.py
> Use pandoc>=3.0 in the tests

- CHANGELOG.md
- pyproject.toml
- src/jupytext/config.py
- src/jupytext/contentsmanager.py
> Use the standard lib `tomllib`, or default to `tomli` if not available

- CHANGELOG.md
- docs/languages.md
- jupyterlab/yarn.lock
- src/jupytext/languages.py
- tests/data/notebooks/inputs/ipynb_xonsh/xonsh_example.ipynb
- tests/data/notebooks/outputs/ipynb_to_Rmd/xonsh_example.Rmd
- tests/data/notebooks/outputs/ipynb_to_hydrogen/xonsh_example.xsh
- tests/data/notebooks/outputs/ipynb_to_md/xonsh_example.md
- tests/data/notebooks/outputs/ipynb_to_myst/xonsh_example.md
- tests/data/notebooks/outputs/ipynb_to_percent/xonsh_example.xsh
- tests/data/notebooks/outputs/ipynb_to_script/xonsh_example.xsh
Hi @mwouts, I have tried following the instructions in the documentation to add support for [Xonsh](https://github.com/xonsh/xonsh).
File extension: `.xsh`
Comment: `"#"`
Kernel: [xonsh-jupyter](https://github.com/xonsh/xontrib-jupyter)
However, on my machine, 2 tests are still failing (even though I did not touch the code):
```python
================================================================================= short test summary info ==================================================================================
FAILED tests/integration/cli/test_execute.py::test_execute_r - AttributeError: outputs
FAILED tests/functional/others/test_pytest.py::test_run_pytest_ok - SystemExit: 4
============================================================ 2 failed, 3123 passed, 88 skipped, 6 …
```
> Add Xonsh support

- .github/workflows/comment-pr.yml
- .github/workflows/publish.yml
- .github/workflows/step_build.yml
- .github/workflows/step_coverage.yml
- .github/workflows/step_tests-conda.yml
- .github/workflows/step_tests-pip.yml
- .github/workflows/step_tests-ui.yml
- CHANGELOG.md
- binder/postBuild
- docs/developing.md
- pyproject.toml
> Don't build the JupyterLab extension by default

- CHANGELOG.md
- src/jupytext/cli.py
> Update the timestamp of the py file only if it is older than that of the nb file

- tests/functional/round_trip/test_myst_header.py
using either a local metadata filter, or a Jupytext configuration file
> Add two examples for #1247

- .pre-commit-config.yaml
- tests/functional/round_trip/test_myst_header.py
Until we figure out what is the problem with `tests/external/simple_external_notebooks/test_read_simple_pandoc.py`
> Deactivate pyupgrade in the pre-commit hooks

- CHANGELOG.md
- docs/languages.md
- src/jupytext/languages.py
- src/jupytext/version.py
- tests/data/notebooks/inputs/ipynb_lua/lua_example.ipynb
- tests/data/notebooks/outputs/ipynb_to_Rmd/lua_example.Rmd
- tests/data/notebooks/outputs/ipynb_to_hydrogen/lua_example.lua
- tests/data/notebooks/outputs/ipynb_to_md/lua_example.md
- tests/data/notebooks/outputs/ipynb_to_myst/lua_example.md
- tests/data/notebooks/outputs/ipynb_to_percent/lua_example.lua
- tests/data/notebooks/outputs/ipynb_to_script/lua_example.lua
I have tried my best in following [the instructions](https://github.com/mwouts/jupytext/blob/main/docs/contributing.md) however was unable to get `pip install -e '.[dev]'` to work.
I would be thankful if someone helped me out by providing a dockerfile such that i can test it in a reproducible environment
> Add language support for Lua

- CHANGELOG.md
- src/jupytext/__init__.py
- src/jupytext/version.py
when `build_jupytext_contents_manager_class` can't be imported, we
define it as a class that re-raise the exception that was encountered.
Relates to #1162
> Fix a typo 

- CHANGELOG.md
- src/jupytext/config.py
- tests/functional/config/test_config.py
> Allow an empty prefix in format dict

- CHANGELOG.md
- docs/languages.md
- src/jupytext/cell_reader.py
- src/jupytext/cell_to_text.py
- src/jupytext/languages.py
- src/jupytext/magics.py
- tests/data/notebooks/inputs/ipynb_go/hello_world_gonb.ipynb
- tests/data/notebooks/outputs/ipynb_to_Rmd/hello_world_gonb.Rmd
- tests/data/notebooks/outputs/ipynb_to_hydrogen/hello_world_gonb.go
- tests/data/notebooks/outputs/ipynb_to_md/hello_world_gonb.md
- tests/data/notebooks/outputs/ipynb_to_myst/hello_world_gonb.md
- tests/data/notebooks/outputs/ipynb_to_percent/hello_world_gonb.go
- tests/data/notebooks/outputs/ipynb_to_script/hello_world_gonb.go
- tests/functional/simple_notebooks/test_read_simple_go.py
- tests/functional/simple_notebooks/test_read_simple_percent.py
> Add support for go notebooks

- src/jupytext/cell_metadata.py
Silences this DeprecationWarning with python 3.13.0b2:
```
/builddir/build/BUILD/python-jupytext-1.16.2-build/BUILDROOT/usr/lib/python3.13/site-packages/jupytext/cell_metadata.py:260: DeprecationWarning: 'maxsplit' is passed as positional argument
options = re.split(r"\s|,", options, 1)
```
> Fix re.split DeprecationWarning

- .github/workflows/step_tests-conda.yml
- .github/workflows/step_tests-pip.yml
- CHANGELOG.md
- docs/install.md
- jupyterlab/jupyterlab_jupytext/__init__.py
- pyproject.toml
- tests/external/jupyter_fs/test_jupyter_fs.py
Closes #1239 
@mwouts What do you think of this change? I have bumped `jupytext` version in tests to use new [`SyncMetaManager`](https://github.com/jpmorganchase/jupyter-fs/blob/4dc6f12486771bfb5b0b1f4bd54367db9a1eb848/jupyterfs/metamanager.py#L169)
> Check `ContentsManager` base class using `inspect`

- .github/workflows/step_tests-ui.yml
as jupyter-fs overrides the integration tests with its owns
> Uninstall jupyter-fs in test-ui

- CHANGELOG.md
- jupyterlab/jupyterlab_jupytext/__init__.py
- src/jupytext/version.py
> Fix Async Contents Manager detection

- .github/workflows/publish.yml
Recently the publish CI has been failing due to the UI test (cf. https://github.com/mwouts/jupytext/actions/runs/9958694800/job/28138283717)
I'd rather have a publish CI that does "just publish"
> Simplify the publish CI to do "just publish"

- CHANGELOG.md
- pyproject.toml
Fixes: the `rst2md` tests fail in the CI #1266
> Require sphinx<8 in tests

- .github/workflows/step_build.yml
- .github/workflows/step_pre-commit.yml
- .github/workflows/update-playwright-snapshots.yml
- jupyterlab/packages/jupyterlab-jupytext-extension/ui-tests/playwright.config.js
- jupyterlab/packages/jupyterlab-jupytext-extension/ui-tests/tests/jupytext-settings.spec.ts
See [comment](https://github.com/mwouts/jupytext/issues/1260#issuecomment-2232440074)
Closes #1230
> Retry flaky UI tests in CI

- .github/workflows/step_tests-pip.yml
- CHANGELOG.md
- environment.yml
- pyproject.toml
- tests/conftest.py
> Test Jupytext with Python 3.13

- .github/workflows/update-playwright-snapshots.yml
> Use gh rather than hub as the latter was removed

- .github/workflows/step_tests-conda.yml
- .github/workflows/step_tests-pip.yml
- .github/workflows/step_tests-ui.yml
- .github/workflows/update-playwright-snapshots.yml
- CHANGELOG.md
The automated update fails, and I could not run the update locally neither.
Relates to #1294
> Skip the playright tests and the jupyter "pre" tests

- CHANGELOG.md
- src/jupytext/cli.py
This PR contains @jlec's fix from #1283 (I have reverted the formatting change and rebase on latest `main`)
>  fix: #1281 pre-commit fails with log.showsignature=True

- CHANGELOG.md
- src/jupytext/contentsmanager.py
- src/jupytext/version.py
When `jupyter-collaboration` is installed, the `format` argument in
text = self.super.get(
alt_path, content=True, type="file", format=format
)["content"]
equals `json`, and because of that we get a `base64` encoding of the notebook inputs instead of the notebook inputs themselves.
That is a very serious issue, as the notebook appears with a single cell that is unreadable. If the user saves or autosaves the notebook then the notebook will be corrupted on disk. In that case, the inputs can be recovered (but not the outputs) with:
```
text = """IyAtLS0K...""" # copy the corrupted cell
print(base64.b64decode("".join(text.splitlines())).decode('utf8'))  # this will recover the .py file
```
This PR addresses this problem by setting `format="text"`, instead of inherited it from the parent call. …
> Ensure that we get the text as text (not json)

- .github/workflows/step_tests-pip.yml
- CHANGELOG.md
- README.md
- src/jupytext/contentsmanager.py
- src/jupytext/version.py
- tests/integration/contents_manager/test_contentsmanager.py
> Implement `require_hash` in the `get` method of Jupytext's content manager

- src/jupytext/cli.py
Based on the issue #1289 I propose a solution using the "-" (minus) instead of "_" (underscore) for the delimiter of original filename and filename of temporary file.
I suggest to take "-" since the "safe" characters to use in filename for all platforms are `[0-9a-zA-Z-._]` while the "_" already interferes with poor chosen python temp filename naming sequence characters. I would also do not take "." since it is already used for the file extension on the right and is more error prone if the file has no extension prefix.
This let us basically only with the "-" as a valid character.
Thanks!
> Use a "-" as a delimeter for filenames of temporary files

- CHANGELOG.md
- src/jupytext/contentsmanager.py
- src/jupytext/version.py
> Combine the two hashes only if the file names differ

- .github/workflows/step_tests-conda.yml
- .github/workflows/step_tests-pip.yml
This is a rebased version of #1297
> Fix failing extension check tests

- pyproject.toml
- src/jupytext/cell_reader.py
- tests/data/notebooks/outputs/sphinx-rst2md_to_ipynb/plot_notebook.ipynb
With this PR, the newer versions of sphinx gallery can be used with `jupytext`.
Sphinx-gallery has kept the rst2cmd function signature since 0.8.0:
- `0.8.0`: https://github.com/sphinx-gallery/sphinx-gallery/blob/05cc570f62dbe4b71ddc57832ba119fc5457ea0d/sphinx_gallery/notebook.py#L72
- `master`: https://github.com/sphinx-gallery/sphinx-gallery/blob/f84a7af3459c053124c34c4c53037228689d3656/sphinx_gallery/notebook.py#L96
As for the changes, the API for headers is tested by sphinx gallery:
https://github.com/sphinx-gallery/sphinx-gallery/blob/05cc570f62dbe4b71ddc57832ba119fc5457ea0d/sphinx_gallery/tests/test_notebook.py#L146-L148
And setting `gallery_conf = {"notebook_images": False}` skips any image embedding:
https://github.com/sphinx-gallery/sphinx-gallery/blob/f84a7af3459c053124c34c4c5303 …
> Support newer versions of sphinx gallery

- .github/dependabot.yml
This PR ensures that dependabot will group all the version updates into a single PR for each `npm` project.
> Update dependabot config to group PRs

- CHANGELOG.md
- tests/integration/contents_manager/test_contentsmanager.py
> Fix issue with send2trash when running tests locally 

- pyproject.toml
- tests/functional/others/test_trust_notebook.py
> Address intermittent test failures

- jupyterlab/packages/jupyterlab-jupytext-extension/src/factory.ts
- jupyterlab/packages/jupyterlab-jupytext-extension/src/index.ts
- jupyterlab/packages/jupyterlab-jupytext-extension/ui-tests/tests/jupytext-notebook.spec.ts
This PR fixes #990.
The cell toolbar is an extension added to the *Notebook* factory from the plugin [`'@jupyterlab/cell-toolbar-extension:plugin'`](https://github.com/jupyterlab/jupyterlab/blob/d470c501f50ad7075413cd89967a1a8a332b9a2f/packages/cell-toolbar-extension/src/index.ts#L76).
With this PR, we make sure that the `cell-toolbar-extension` is activated, and add all the extensions of the *Notebook* factory to the *Jupytext Notebook* factory.
> Fix the cell toolbar for Jupytext Notebook factory

- CHANGELOG.md
- pyproject.toml
- src/jupytext/version.py
- tools/absolute_links_in_readme.py
> Use absolute links on PyPI

- src/jupytext/header.py
- src/jupytext/jupytext.py
- src/jupytext/metadata_filter.py
- src/jupytext/myst.py
- tests/data/notebooks/outputs/ipynb_to_myst/jupyter_with_raw_cell_on_top.md
- tests/functional/metadata/test_metadata_filter.py
- tests/functional/metadata/test_metadata_filters_from_config.py
- tests/functional/round_trip/test_myst_header.py
The "root_level_metadata_filter" I just introduced had a few flaws.
1) The setting of `myst._DEFAULT_ROOT_LEVEL_METADATA` to a list of a three keys is not enough to prevent disruption of existing notebooks; the new setting introduced here is "all" (which is now exactly how the myst format has been working). That "all" makes subsequent separation of metadata and raw cell frontmatter harder, but is solved by storing the frontmatter keys in `jupytext.root_level_metadata_filter`. The "root_level_metadata_filter" key would only be injected if not set by the user and only if there is a raw cell on top (i.e. unlikely to be encountered at all except by folks switching to md:myst from md format).
2) Setting "root_level_metadata_filter" to "-all" in user config was not compatible with the use of …
> updates to the root_level_metadata_filter config handling

- CHANGELOG.md
- README.md
- jupyterlab/packages/jupyterlab-jupytext-extension/CHANGELOG.md
- jupyterlab/packages/jupyterlab-jupytext-extension/package.json
- src/jupytext/jupytext.py
- src/jupytext/version.py
- tests/integration/contents_manager/test_contentsmanager.py
This PR contains the following changes
- We order the notebook metadata for consistency with v1.16 (see https://github.com/mwouts/jupytext/pull/1368#issuecomment-2765241981)
- I bumped the version number to 1.17.0
> Version 1.17.0

- .github/workflows/step_tests-pip.yml
- CHANGELOG.md
- environment.yml
- pyproject.toml
- src/jupytext/version.py
Python 3.8 has reached its EOL, and `hatch` fails to install in the recent CI runs: https://github.com/mwouts/jupytext/actions/runs/15322535856
> Drop support for Python 3.8

- src/jupytext/formats.py
- tests/data/notebooks/inputs/ipynb_cpp/root_cpp.ipynb
- tests/functional/others/test_auto_ext.py
Recent versions of the [ROOT data analysis framework](https://root.cern.ch/) offer a [C++ kernel](https://github.com/root-project/root/tree/master/bindings/jupyroot#c-rootbook) for Jupyter notebooks. The metadata saved by ROOT into these notebooks lists ".C" as the file extension rather than the more standard ".cpp"
This pull request adds handling of this file extension for the C++ language. An example ROOT C++ notebook is included that passes unit tests after the proposed code changes.
> Add handling for ROOT-flavored C++ notebooks that use the ".C" extension

- .github/codecov.yml
- CHANGELOG.md
- src/jupytext/cli.py
This PR changes the output of `jupytext --help` in the following way:
```
(jupytext-dev) jupytext $ jupytext --help > v1.17.3
(jupytext-dev) jupytext $ jupytext --help > v1.17.2
(jupytext-dev) jupytext $ diff v1.17.2 v1.17.3
25,40c25,46
<                         'py', 'R', ..., 'auto' (script extension matching the
<                         notebook language), or a combination of an extension
<                         and a format name, e.g. md:myst, md:markdown,
<                         md:pandoc or py:light, py:percent, py:sphinx,
<                         py:hydrogen, py:nomarker. The default format for
<                         scripts is the 'percent' format, which uses '# %%' as
<                         cell markers and is compatible with VS Code and
< …
```
> Document all the extensions supported by `jupytext --to`

- CHANGELOG.md
- src/jupytext/config.py
- tests/functional/cli/test_cli.py
- tests/functional/config/test_config.py
- tests/integration/contents_manager/test_contentsmanager.py
that was not the case in Jupytext v1.17.2 when the configuration has e.g. formats="ipynb,py:percent"
Closes #1418
> Fix: a round trip on a simple Python file leaves it unchanged
