jupytext/cell_reader.py
https://docs.python.org/3/library/stdtypes.html#str.startswith says:
* __prefix__ _can also be a tuple of prefixes to look for._
=> First parameter of str.startswith() can be a tuple

jupytext/cell_to_text.py, jupytext/cli.py, jupytext/header.py, jupytext/jupytext.py, requirements-dev.txt, tests/test_read_simple_markdown.py, tests/test_stringparser.py, tests/utils.py
A first little cosmetic contribution.
=> Fix some style issues (from flake8 and SonarLint)

jupytext/cli.py, tests/test_cli.py
Fixes https://github.com/mwouts/jupytext/issues/84.
=> Output to stdout shouldn't append extra newline

README.md
=> Modify metadata filtering doc

README.md
https://github.com/mwouts/jupytext/issues/121
=> Improve pre-commit doc

README.md
=> add jupyterhub warning to readme

README.md
More verbose description of split_at_heading
=> Rewrite docs on split_at_heading

docs/conf.py
I *think* this will fix our RTD errors
=> adding master doc config

.travis.yml, jupytext/contentsmanager.py, jupytext/kernels.py, jupytext/languages.py, jupytext/metadata_filter.py, jupytext/paired_paths.py, setup.cfg, tests/notebooks/ipynb_js/ijavascript.ipynb, tests/notebooks/ipynb_ts/itypescript.ipynb, tests/notebooks/mirror/ipynb_to_Rmd/ijavascript.Rmd, tests/notebooks/mirror/ipynb_to_Rmd/itypescript.Rmd, tests/notebooks/mirror/ipynb_to_md/ijavascript.md, tests/notebooks/mirror/ipynb_to_md/itypescript.md, tests/notebooks/mirror/ipynb_to_pandoc/ijavascript.md, tests/notebooks/mirror/ipynb_to_pandoc/itypescript.md, tests/notebooks/mirror/ipynb_to_percent/ijavascript.js, tests/notebooks/mirror/ipynb_to_percent/itypescript.ts, tests/notebooks/mirror/ipynb_to_script/ijavascript.js, tests/notebooks/mirror/ipynb_to_script/itypescript.ts, tests/test_mirror.py, tests/test_pep8.py
this PR adds support for files using [IJavascript](https://github.com/n-riesco/ijavascript) and [ITypescript](https://github.com/nearbydelta/itypescript) kernels.
as discussed in #249
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mwouts/jupytext/250)
=> add support for javascript and typescript

.travis.yml, tests/test_cli.py
Restore the tests on Python 3.8 (#269)
=> Pytest 5.0.0

binder/requirements.txt
=> Use JupyterLab 1.0 on Binder

README.md, jupytext/cli.py, tests/test_cli.py
=> Jupytext sync ignores unpaired notebooks

CONTRIBUTING.md, HISTORY.rst, docs/using-cli.md, jupytext/jupytext.py, requirements-dev.txt, tests/test_read_write_functions.py
And document how to use Jupytext with the pre-commit package #292
=> Improve usability of read and write functions

.travis.yml
=> Travis with conda

jupytext/cell_reader.py, jupytext/cell_to_text.py, jupytext/jupytext.py, tests/notebooks/mirror/ipynb_to_Rmd/Reference Guide for Calysto Scheme.Rmd, tests/notebooks/mirror/ipynb_to_hydrogen/World population.py, tests/notebooks/mirror/ipynb_to_md/Reference Guide for Calysto Scheme.md, tests/test_mirror.py, tests/test_read_simple_markdown.py, tests/test_read_simple_rmd.py
- Markdown cells can now contain code
- Markdown and R Markdown formats are tested on all the example notebooks
=> Fix code in markdown cells

tests/test_read_simple_markdown.py
Additional test motivated by #66
=> Test the transition from Jupytext Markdown 1.1 to 1.2

jupytext/cli.py, jupytext/compare.py, tests/test_active_cells.py, tests/test_black.py, tests/test_cli.py, tests/test_compare.py, tests/test_contentsmanager.py, tests/test_escape_magics.py, tests/test_formats.py, tests/test_header.py, tests/test_paired_paths.py, tests/test_pep8.py, tests/test_preserve_empty_cells.py, tests/test_read_all_py.py, tests/test_read_folding_markers.py, tests/test_read_simple_R.py, tests/test_read_simple_bare.py, tests/test_read_simple_clojure.py, tests/test_read_simple_hydrogen.py, tests/test_read_simple_ipynb.py, tests/test_read_simple_julia.py, tests/test_read_simple_markdown.py, tests/test_read_simple_pandoc.py, tests/test_read_simple_percent.py, tests/test_read_simple_python.py, tests/test_read_simple_rmd.py, tests/test_read_simple_scheme.py, tests/test_read_simple_sphinx.py, tests/test_read_write_functions.py, tests/test_rmd_to_ipynb.py
All the calls to `compare` follow the pattern `compare(actual, expected)`.
=> Compare actual expected

HISTORY.rst, jupytext/cell_reader.py, jupytext/cell_to_text.py, jupytext/magics.py, tests/test_cli.py, tests/test_escape_magics.py, tests/test_read_simple_python.py
=> Comment IPython's magic help command

packages/labextension/README.md
README.md update for issue #350
=> README.md clarification for jupyterlab-jupytext

docs/faq.md, docs/formats.md
- More detailed description of the Markdown and the light/percent formats
- Formats specifications updated (multiline comments in the percent format, key="value" everywhere for the metadata)
=> Improved description of formats

jupytext/cli.py, jupytext/version.py, tests/test_contentsmanager.py
=> Update the timestamp of the source notebook only for paired notebooks

tests/notebooks/mirror/ipynb_to_pandoc/julia_benchmark_plotly_barchart.md
=> Notebook regenerated with Pandoc 2.8.0.1

jupytext/header.py, tests/test_header.py
empty line is legal in YAML config section
=> Fix #404 empty line handling in metadata

.travis.yml, CHANGELOG.md, LICENSE, jupytext/combine.py, jupytext/paired_paths.py, jupytext/version.py, tests/test_cli.py, tests/test_mirror.py
This solves an issue reported by @lwasser at #338.
=> Ignore non notebook files in the pre-commit mode

CHANGELOG.md, jupytext/cli.py, tests/test_cli.py
=> Fix set format in folder

CHANGELOG.md, README.md, docs/introduction.md, jupytext/languages.py, jupytext/version.py, tests/notebooks/ipynb_sos/jupytext_replication.ipynb, tests/notebooks/mirror/ipynb_to_Rmd/jupytext_replication.Rmd, tests/notebooks/mirror/ipynb_to_hydrogen/jupytext_replication.sos, tests/notebooks/mirror/ipynb_to_md/jupytext_replication.md, tests/notebooks/mirror/ipynb_to_percent/jupytext_replication.sos, tests/notebooks/mirror/ipynb_to_script/jupytext_replication.sos
The credit for the SoS notebook example goes to @thomaspernet.
This closes #453.
=> Support script of script (SoS) notebooks

jupytext/version.py, tests/test_read_simple_python.py
=> Test notebook starting with two raw cells

CHANGELOG.md, jupytext/combine.py, jupytext/stringparser.py, tests/test_combine.py, tests/test_stringparser.py
`""""` (a quadruple double quote) at the end of a multiline string should not cause any issue (#460)
=> Additional test/fix for the string parser

CHANGELOG.md, tests/test_read_simple_matlab.py
=> How to add custom tags in a matlab file

.github/workflows/continuous-integration-conda.yml, .github/workflows/continuous-integration-pip.yml, environment.yml, tests/test_cli.py, tests/test_using_cli.py
=> Setup GitHub Actions

CHANGELOG.md, docs/using-cli.md, tests/test_cli.py, tests/test_using_cli.py, tests/utils.py
=> Test and document how to create a YAML header with --set-kernel and/or --set-formats

tests/test_cli.py
=> Skip the test if a timeout occurs during notebook execution

jupytext/config.py, jupytext/version.py
=> Search for a config file in USERSPROFILE and ALLUSERSPROFILE on Windows

tests/test_escape_magics.py
Add a test that document the continuation line approach for #513
=> Test the continuation line approach for the %%configure magic

.github/workflows/continuous-integration-conda.yml, environment-ci.yml, environment.yml, tests/test_cli.py, tests/test_execute.py
Following @goanpeca's suggestion, I am trying to setup a cache for conda packages.
See also: https://github.com/goanpeca/setup-miniconda#caching
=> Use a package cache on the conda-CI

CHANGELOG.md, jupytext/formats.py, tests/test_cli.py
=> Improve version mismatch error message

jupytext/languages.py
Mini PR for adding .resource support for Robot Framework. No tests added, just a file extension addition.
=> support for Robot Framework .resource files.

.github/workflows/continuous-integration-conda.yml, environment-ci.yml, environment.yml, tests/test_pre_commit.py, tests/utils.py
=> Conda CI: install optional dependencies with conda --freeze-installed

tests/test_execute.py
=> Increase execute timeout on "jupyter nbconvert --execute" commands

CHANGELOG.md, environment-ci.yml, jupytext/version.py
=> Version 1.5.1

docs/paired-notebooks.md
=> Fix broken link in paired-notebooks documentation

CHANGELOG.md, CONTRIBUTING.md, jupytext/cell_metadata.py, jupytext/magics.py, jupytext/version.py, tests/test_cell_metadata.py, tests/test_escape_magics.py, tests/test_read_simple_python.py
=> Preserve the indentation of magic commands

CHANGELOG.md, jupytext/config.py, tests/test_config.py
=> Jupytext.py is not a configuration file

CHANGELOG.md, binder/postBuild, binder/requirements.txt
=> Install jupytext from source on MyBinder

CHANGELOG.md, jupytext/header.py, tests/notebooks/mirror/ipynb_to_Rmd/simple-helloworld.Rmd, tests/notebooks/mirror/ipynb_to_Rmd/tailrecursive-factorial.Rmd, tests/notebooks/mirror/ipynb_to_md/simple-helloworld.md, tests/notebooks/mirror/ipynb_to_md/tailrecursive-factorial.md, tests/test_unicode.py
=> No encoding comments in Markdown or R Markdown files

.github/workflows/continuous-integration-conda.yml, CHANGELOG.md, docs/using-cli.md, environment.yml, jupytext/cli.py, tests/test_isort.py, tests/test_using_cli.py, tests/utils.py
=> Test and document how to use isort on a notebook

CHANGELOG.md, tests/test_cli_config.py, tests/test_cm_config.py
=> Test that notebooks paired through a configuration file are left unmodified

jupytext/cell_reader.py, jupytext/cell_to_text.py, jupytext/cli.py, jupytext/config.py, jupytext/doxygen.py, jupytext/formats.py, tests/test_doxygen.py
=> New option doxygen_equation_markers

docs/formats.md, jupytext/myst.py, tests/test_ipynb_to_myst.py
A PR on top of your PR, on top of my PR 😆
=> Jupytext depends on markdownitpy (#601 update)

CHANGELOG.md, jupytext/cell_to_text.py, jupytext/config.py, jupytext/formats.py, jupytext/jupytext.py, jupytext/languages.py, tests/test_custom_cell_magics.py
=> New option custom_cell_magics

.github/workflows/continuous-integration-pip.yml, CHANGELOG.md, jupytext/config.py, jupytext/contentsmanager.py, jupytext/formats.py, jupytext/header.py, jupytext/pandoc.py, tests/test_cm_config.py, tests/test_contentsmanager.py
=> Jupytext works with jupyterfs

.github/workflows/codeql-analysis.yml, .github/workflows/continuous-integration-conda.yml, .github/workflows/continuous-integration-pip.yml, .github/workflows/pre-commit.yml, .gitignore, .pre-commit-config.yaml, CONTRIBUTING.md, codecov.yml, environment.yml, jupytext/__init__.py, jupytext/cell_reader.py, jupytext/formats.py, jupytext/header.py, jupytext/jupytext.py, jupytext/myst.py, requirements-dev.txt, tests/test_cli_config.py, tests/utils.py, tox.ini
=> Ci improvements

codecov.yml, tests/test_trust_notebook.py
May close #639 ?
This is the change suggested by Tom at
https://community.codecov.io/t/codecov-patch-keeps-failing-and-i-cannot-turn-it-off/2094
=> Update codecov.yml according to Tom's recommendation

.github/workflows/codeql-analysis.yml, .github/workflows/continuous-integration-conda.yml, .github/workflows/continuous-integration-pip.yml, CHANGELOG.md
=> Skip the CI jobs when only CHANGELOG is updated

tests/test_cli_config.py
=> Test that glob expressions can be used on Windows

README.md, docs/index.md, setup.py
This indeed fixes #648 , see https://test.pypi.org/project/jupytext/1.7.0rc0/ :smile:
=> Convert the doc/xx.md links in README.md to links to RTD

CHANGELOG.md, README.md, docs/conf.py, docs/config.md, docs/doc-requirements.txt, docs/examples.md, docs/faq.md, docs/index.md, docs/languages.md, docs/paired-notebooks.md, docs/using-cli.md, docs/using-library.md, docs/using-pre-commit.md, environment.yml
This also fixes #650 , a long standing issue.
=> Use myst_parser to render the Jupytext documentation

.readthedocs.yml, CONTRIBUTING.md, docs/environment.yml, docs/index.md
This is inspired by https://github.com/jupyter/kernel_gateway, and will hopefully fix #650
=> Use a conda environment on RTD

environment-ci.yml, environment.yml, tests/notebooks/mirror/ipynb_to_pandoc/julia_benchmark_plotly_barchart.md
And switch to pandoc 2.11
This fixes an issue seen in the recent runs of the CI (e.g. #664 )
=> Update YAML header in Julia md:pandoc notebook

jupytext/contentsmanager.py
Unlike the other errors, which are "internal" #638, we want to make sure that this one is displayed in Jupyter.
=> Error "ipynb more recent than text file" is HTTP 400

.github/workflows/continuous-integration.yml, codecov.yml, docs/CHANGELOG.md, jupytext/version.py, setup.py, tox.ini
=> Drop explicit support for Python 2.7

.github/workflows/continuous-integration.yml, codecov.yml, jupytext/cell_metadata.py, requirements.txt, setup.py, tests/conftest.py, tests/test_active_cells.py, tests/test_cell_metadata.py, tests/test_cli.py, tests/test_cm_config.py, tests/test_contentsmanager.py, tests/test_hide_remove_input_outputs_rmarkdown.py, tests/test_ipynb_to_myst.py, tests/test_knitr_spin.py, tests/test_mirror.py, tests/test_paired_paths.py, tests/test_pre_commit.py, tests/test_read_simple_python.py, tests/test_read_simple_rmd.py, tests/test_rmd_to_ipynb.py, tests/test_unicode.py, tests/utils.py
This is a pre-requisite for #683 .
However I can't get the CI to work.
Help appreciated!
=> Drop support for Python 3.5

CONTRIBUTING.md, setup.py
This is another attempt to fix #706
=> Don't build the jupyterlab-jupytext extension unless BUILD_JUPYTERLAB_EXTENSION (or CI) is True

MANIFEST.in, docs/CHANGELOG.md
=> Filter out node_modules

docs/CHANGELOG.md, jupytext/version.py, packages/labextension/CHANGELOG.md, packages/labextension/package.json, packages/labextension/yarn.lock
This will solve a security issue, cf. https://github.com/jupyterlab/jupyterlab/pull/9809
@martinRenou I guess that I should prepare a new release of the main package, in addition of this file?
=> Update the dependencies of the JupyterLab-Jupytext extension

docs/CHANGELOG.md, jupytext/jupytext.py, jupytext/version.py, tests/test_metadata_filter.py
=> Update format with format options in the notebook metadata (md:myst and md:pandoc)

docs/CHANGELOG.md, environment-ci.yml, environment.yml, jupytext/myst.py, requirements.txt, setup.py
This is the same as #769 but with a few additional changes in requirements.txt, and in the environment files.
=> Markdown it py v1

tests/test_cli_config.py
This PR provides an additional test for #771
=> Test pairing to multiple formats using a config file

docs/CHANGELOG.md, jupytext/version.py, tests/test_ipynb_to_myst.py
=> Add a test to document when pygment lexers appear in MyST Markdown

docs/CHANGELOG.md, jupytext/version.py, packages/labextension/CHANGELOG.md, packages/labextension/package.json, packages/labextension/yarn.lock
Fixes #783 and a few other security vulnerabilities
=> Update jlab extension

docs/CHANGELOG.md, jupytext/cli.py, tests/test_pre_commit_mode.py
=> New function git_timestamp that returns the commit timestamp

docs/CHANGELOG.md, packages/labextension/CHANGELOG.md, packages/labextension/package.json, packages/labextension/yarn.lock
=> Upgrade all the jupyterlab-jupytext extension dependencies

docs/CHANGELOG.md, requirements.txt, setup.py
As suggested by @kloczek in [this comment](https://github.com/mwouts/jupytext/issues/814#issuecomment-878867707)
@kloczek, @chrisjsewell , does this PR sounds right for each of you? Thanks
=> Explicit dependency on `mdit-py-plugins`

docs/CHANGELOG.md, docs/languages.md, jupytext/cell_reader.py, jupytext/cell_to_text.py, jupytext/formats.py, jupytext/header.py, jupytext/languages.py, jupytext/magics.py, tests/notebooks/ipynb_ocaml/ocaml_notebook.ipynb, tests/notebooks/mirror/ipynb_to_Rmd/ocaml_notebook.Rmd, tests/notebooks/mirror/ipynb_to_hydrogen/ocaml_notebook.ml, tests/notebooks/mirror/ipynb_to_md/ocaml_notebook.md, tests/notebooks/mirror/ipynb_to_myst/ocaml_notebook.md, tests/notebooks/mirror/ipynb_to_percent/ocaml_notebook.ml, tests/notebooks/mirror/ipynb_to_script/ocaml_notebook.ml, tests/test_cells.py, tests/test_read_simple_ocaml.py
=> OCaml support

docs/CHANGELOG.md, jupytext/cli.py, jupytext/contentsmanager.py, jupytext/pairs.py, tests/test_cli.py, tests/test_contentsmanager.py, tests/test_pre_commit_4_sync_execute.py, tests/test_pre_commit_5_reformat_markdown.py, tests/test_pre_commit_mode.py
Jupyter does not fail to open outdated ipynb files if their content match the paired text file
Closes #799
=> New 'jupytext --diff' command

jupytext/myst.py, tests/test_read_empty_text_notebook.py
=> Empty MyST files are valid notebooks

docs/CHANGELOG.md, environment-ci.yml, environment.yml, requirements-dev.txt, tests/test_cell_metadata.py
=> Test Jupytext with pytest-randomly

docs/CHANGELOG.md, jupytext/cli.py
This is the same as #905, but I have added the pre-commit hooks & a CHANGELOG entry
=> Improve cli message

tests/test_cli.py
=> Document how to set a shebang with --update-metadata

.github/workflows/continuous-integration.yml, codecov.yml, docs/CHANGELOG.md, jupytext/contentsmanager.py, tests/test_pep8.py
=> Import base contentsmanager from jupyter server

.pre-commit-config.yaml, docs/CHANGELOG.md, jupytext/formats.py, jupytext/header.py, jupytext/jupytext.py, jupytext/languages.py, tests/notebooks/ipynb_maxima/maxima_example.ipynb, tests/notebooks/mirror/ipynb_to_Rmd/maxima_example.Rmd, tests/notebooks/mirror/ipynb_to_hydrogen/maxima_example.mac, tests/notebooks/mirror/ipynb_to_md/maxima_example.md, tests/notebooks/mirror/ipynb_to_myst/maxima_example.md, tests/notebooks/mirror/ipynb_to_percent/maxima_example.mac, tests/notebooks/mirror/ipynb_to_script/maxima_example.mac, tests/test_cli_config.py, tests/test_contentsmanager.py, tests/test_header.py, tests/test_jupytext_nbconvert_round_trip.py
=> Support maxima language

.pre-commit-config.yaml, jupytext/magics.py, tests/test_escape_magics.py
=> FIx issue #938

docs/CHANGELOG.md, packages/labextension/CHANGELOG.md, packages/labextension/package.json, packages/labextension/yarn.lock
=> Upgrade the Jupyter Lab extension dependencies

docs/CHANGELOG.md, jupytext/metadata_filter.py, tests/test_cell_metadata.py
=> Filter out empty tags

codecov.yml, docs/CHANGELOG.md, tests/test_pre_commit_scripts.py
Fixes an issue seen locally with `git==2.34.1`
=> Use main as the default git branch in tests

binder/postBuild, binder/requirements.txt
This PR can be tested at https://mybinder.org/v2/gh/mwouts/jupytext/require_nbclassic_0.5.5?filepath=demo
=> Definitive workaround for #1051

docs/CHANGELOG.md, jupytext/formats.py, jupytext/version.py, tests/test_read_simple_markdown.py
=> Fix opening of notebooks with empty YAML header

docs/CHANGELOG.md, jupytext/cell_metadata.py, tests/test_read_simple_rmd.py
=> Fix single quote in double quotes in R Markdown options

docs/CHANGELOG.md, jupytext/contentsmanager.py, tests/test_contentsmanager.py
=> Create prefix dir before moving paired notebooks

docs/CHANGELOG.md, jupytext/stringparser.py, tests/test_read_simple_rmd.py
=> Ignore commented quotes

.github/workflows/continuous-integration.yml
This PR addresses the additional recommendations at #1084
=> Follow-ups on the CI

.pre-commit-config.yaml, docs/CHANGELOG.md, jupytext/pandoc.py
Same as #1099 but with `black` formatting and an entry in the CHANGELOG
=> Add support to Pandoc 3

src/jupytext/cell_reader.py, tests/functional/simple_notebooks/test_read_simple_rmd.py
=> The bibliography entry in Rmd documents is not code

.github/workflows/step_comment-pr.yml
rather than pull_request to make the comments work on PR
https://github.com/marketplace/actions/comment-pull-request
=> Use pull_request_target event

jupyterlab/packages/jupyterlab-jupytext-extension/src/utils.ts, jupyterlab/scripts/install_extension.py
Just minor spelling corrections
=> Spelling corrections

.github/workflows/step_tests-pip.yml, CHANGELOG.md
This is a temporary change until we find the proper fix to #1255
=> Deactivate the Quarto tests on the CI

tests/external/pre_commit/test_pre_commit_scripts.py
Now that `black` fixes trailing white spaces we can't expect `flake8` to fail, so I am moving that part of the test to a distinct test.
=> Fix the CI

CHANGELOG.md, LICENSE, jupyterlab/packages/jupyterlab-jupytext-extension/CHANGELOG.md, jupyterlab/yarn.lock, src/jupytext/version.py
This PR might address some of the https://github.com/mwouts/jupytext/security/dependabot alerts
=> Update the dependencies of the jupyterlab extension

jupyterlab/jupyterlab_jupytext/__init__.py
just missed a f"" and added it.
=> add missing format string

CHANGELOG.md, docs/languages.md, src/jupytext/languages.py, src/jupytext/magics.py, src/jupytext/version.py, tests/data/notebooks/inputs/ipynb_logtalk/logtalk_notebook.ipynb, tests/data/notebooks/outputs/ipynb_to_Rmd/logtalk_notebook.Rmd, tests/data/notebooks/outputs/ipynb_to_hydrogen/logtalk_notebook.lgt, tests/data/notebooks/outputs/ipynb_to_md/logtalk_notebook.md, tests/data/notebooks/outputs/ipynb_to_myst/logtalk_notebook.md, tests/data/notebooks/outputs/ipynb_to_percent/logtalk_notebook.lgt, tests/data/notebooks/outputs/ipynb_to_script/logtalk_notebook.lgt
This PR includes @pmoura's addition of the logtalk language #1308
=> Version 1.16.7

.github/workflows/step_coverage.yml, .github/workflows/step_static-analysis.yml, .github/workflows/step_tests-conda.yml, .github/workflows/step_tests-pip.yml
=> Update the codecov and codeql actions

CHANGELOG.md, tests/integration/cli/test_cli_pipe.py
This PR adds a test to confirm that the issue #1267 is gone
Closes #1267
=> Reproduce #1267

CHANGELOG.md, src/jupytext/cli.py, tests/functional/cli/test_cli.py
=> Enforce the quiet option in the pipe mode

CHANGELOG.md, pyproject.toml, src/jupytext/version.py, tools/absolute_links_in_readme.py
Error seen at https://github.com/mwouts/jupytext/actions/runs/14011438651/job/39231750230
```
Checking dist/README_with_absolute_links.md: ERROR    InvalidDistribution: Unknown distribution format:
'README_with_absolute_links.md'
```
=> Fix publish error

src/jupytext/version.py
This is in order to build a RC version that includes #1368
=> Version 1.17.0rc2

src/jupytext/myst.py
Fixes #1370.
The `myst.from_nbnode` function does not catch all `NotebookNode` objects in its recursion (it passes over lists of `NotebookNode` objects). Rather than fix that, we can replace it with the SafeRepresenter update used in `myst.header`.
=> replace from_nbnode with SafeRepresenter

CHANGELOG.md, src/jupytext/async_contentsmanager.py, src/jupytext/sync_contentsmanager.py, src/jupytext/version.py, tests/functional/others/test_trust_notebook.py
=> Don't open the file to be renamed unless it is a notebook

.git-blame-ignore-revs, CHANGELOG.md, src/jupytext/version.py
=> Add git blame ignore revs

CHANGELOG.md, src/jupytext/async_contentsmanager.py, src/jupytext/sync_contentsmanager.py
=> Don't import `notebook` when `jupyter_server` is available
